<?php

//
// WARNING: Do not edit by hand, this file was generated by Crank:
// https://github.com/gocardless/crank
//

// Code Sample Tests
// These tests verify that the documentation code samples are syntactically valid
// and can execute against a mocked API without errors.
//
// IMPORTANT: These tests do NOT verify business logic - they only verify that
// the code samples compile and execute without syntax errors.

namespace GoCardlessPro\CodeSamples;

use PHPUnit\Framework\TestCase;
use GoCardlessPro\Environment;

class BillingRequestFlowsCodeSamplesTest extends TestCase
{
    protected $mock;
    protected $client;

    public function setUp(): void
    {
        parent::setUp();
        $this->mock = new \GuzzleHttp\Handler\MockHandler([]);
        $handler = \GuzzleHttp\HandlerStack::create($this->mock);

        $mock_http_client = new \GuzzleHttp\Client([
            'handler' => $handler,
            'http_errors' => false
        ]);
        $this->client = new \GoCardlessPro\Client(
            array(
                'access_token' => 'SECRET_TOKEN',
                'environment' => Environment::LIVE,
                'http_client' => $mock_http_client
            )
        );
    }






    public function testCreateCodeSample()
    {
        $this->expectNotToPerformAssertions();

        // Mock response - enqueue multiple times to handle code samples with multiple API calls
        $responseBody = '{ "billing_request_flows": {} }';
        for ($i = 0; $i < 5; $i++) {
            $this->mock->append(new \GuzzleHttp\Psr7\Response(200, [], $responseBody));
        }

        // Suppress output from code samples
        ob_start();

        $client = $this->client;

        $client->billingRequestFlows()->create([
          "params" => [
            "redirect_uri" => "https://my-company.com/landing",
            "exit_uri" => "https://my-company.com/exit",
            "prefilled_customer" => [
              "given_name" => "Frank",
              "family_name" => "Osborne",
              "email" => "frank.osborne@acmeplc.com"
            ],
            "links" => [
              "billing_request" => "BRQ123"
            ]
          ]
        ]);

        ob_end_clean();
    }




    public function testInitialiseCodeSample()
    {
        $this->expectNotToPerformAssertions();

        // Mock response - enqueue multiple times to handle code samples with multiple API calls
        $responseBody = '{ "billing_request_flows": {} }';
        for ($i = 0; $i < 5; $i++) {
            $this->mock->append(new \GuzzleHttp\Psr7\Response(200, [], $responseBody));
        }

        // Suppress output from code samples
        ob_start();

        $client = $this->client;

        $client->billingRequestFlows()->initialise("BRF123");

        ob_end_clean();
    }
}
