<?php

//
// WARNING: Do not edit by hand, this file was generated by Crank:
// https://github.com/gocardless/crank
//

// Code Sample Tests
// These tests verify that the documentation code samples are syntactically valid
// and can execute against a mocked API without errors.
//
// IMPORTANT: These tests do NOT verify business logic - they only verify that
// the code samples compile and execute without syntax errors.

namespace GoCardlessPro\CodeSamples;

use PHPUnit\Framework\TestCase;
use GoCardlessPro\Environment;

class CustomerBankAccountsCodeSamplesTest extends TestCase
{
    protected $mock;
    protected $client;

    public function setUp(): void
    {
        parent::setUp();
        $this->mock = new \GuzzleHttp\Handler\MockHandler([]);
        $handler = \GuzzleHttp\HandlerStack::create($this->mock);

        $mock_http_client = new \GuzzleHttp\Client([
            'handler' => $handler,
            'http_errors' => false
        ]);
        $this->client = new \GoCardlessPro\Client(
            array(
                'access_token' => 'SECRET_TOKEN',
                'environment' => Environment::LIVE,
                'http_client' => $mock_http_client
            )
        );
    }






    public function testCreateCodeSample()
    {
        $this->expectNotToPerformAssertions();

        // Mock response - enqueue multiple times to handle code samples with multiple API calls
        $responseBody = '{ "customer_bank_accounts": {} }';
        for ($i = 0; $i < 5; $i++) {
            $this->mock->append(new \GuzzleHttp\Psr7\Response(200, [], $responseBody));
        }

        // Suppress output from code samples
        ob_start();

        $client = $this->client;

        $client->customerBankAccounts()->create([
          "params" => ["account_number" => "55779911",
                       "branch_code" => "200000",
                       "account_holder_name" => "Frank Osborne",
                       "country_code" => "GB",
                       "links" => ["customer" => "CU123"]]
        ]);

        ob_end_clean();
    }




    public function testListCodeSample()
    {
        $this->expectNotToPerformAssertions();

        // Mock response - enqueue multiple times to handle code samples with multiple API calls
        $responseBody = '{ "customer_bank_accounts": [{}], "meta": { "cursors": {}, "limit": 50 } }';
        for ($i = 0; $i < 5; $i++) {
            $this->mock->append(new \GuzzleHttp\Psr7\Response(200, [], $responseBody));
        }

        // Suppress output from code samples
        ob_start();

        $client = $this->client;

        $client->customerBankAccounts()->list();

        $client->customerBankAccounts()->list([
          "params" => ["customer" => "CU123",
                       "enabled" => true]
        ]);

        ob_end_clean();
    }




    public function testGetCodeSample()
    {
        $this->expectNotToPerformAssertions();

        // Mock response - enqueue multiple times to handle code samples with multiple API calls
        $responseBody = '{ "customer_bank_accounts": {} }';
        for ($i = 0; $i < 5; $i++) {
            $this->mock->append(new \GuzzleHttp\Psr7\Response(200, [], $responseBody));
        }

        // Suppress output from code samples
        ob_start();

        $client = $this->client;

        $client->customerBankAccounts()->get("BA123");

        ob_end_clean();
    }




    public function testUpdateCodeSample()
    {
        $this->expectNotToPerformAssertions();

        // Mock response - enqueue multiple times to handle code samples with multiple API calls
        $responseBody = '{ "customer_bank_accounts": {} }';
        for ($i = 0; $i < 5; $i++) {
            $this->mock->append(new \GuzzleHttp\Psr7\Response(200, [], $responseBody));
        }

        // Suppress output from code samples
        ob_start();

        $client = $this->client;

        $client->customerBankAccounts()->update("BA123", [
          "params" => ["metadata" => ["key" => "value"]]
        ]);

        ob_end_clean();
    }




    public function testDisableCodeSample()
    {
        $this->expectNotToPerformAssertions();

        // Mock response - enqueue multiple times to handle code samples with multiple API calls
        $responseBody = '{ "customer_bank_accounts": {} }';
        for ($i = 0; $i < 5; $i++) {
            $this->mock->append(new \GuzzleHttp\Psr7\Response(200, [], $responseBody));
        }

        // Suppress output from code samples
        ob_start();

        $client = $this->client;

        $client->customerBankAccounts()->disable("BA123");

        ob_end_clean();
    }
}
