<?php

//
// WARNING: Do not edit by hand, this file was generated by Crank:
// https://github.com/gocardless/crank
//

// Code Sample Tests
// These tests verify that the documentation code samples are syntactically valid
// and can execute against a mocked API without errors.
//
// IMPORTANT: These tests do NOT verify business logic - they only verify that
// the code samples compile and execute without syntax errors.

namespace GoCardlessPro\CodeSamples;

use PHPUnit\Framework\TestCase;
use GoCardlessPro\Environment;

class InstalmentSchedulesCodeSamplesTest extends TestCase
{
    protected $mock;
    protected $client;

    public function setUp(): void
    {
        parent::setUp();
        $this->mock = new \GuzzleHttp\Handler\MockHandler([]);
        $handler = \GuzzleHttp\HandlerStack::create($this->mock);

        $mock_http_client = new \GuzzleHttp\Client([
            'handler' => $handler,
            'http_errors' => false
        ]);
        $this->client = new \GoCardlessPro\Client(
            array(
                'access_token' => 'SECRET_TOKEN',
                'environment' => Environment::LIVE,
                'http_client' => $mock_http_client
            )
        );
    }






    public function testCreateWithDatesCodeSample()
    {
        $this->expectNotToPerformAssertions();

        // Mock response - enqueue multiple times to handle code samples with multiple API calls
        $responseBody = '{ "instalment_schedules": {} }';
        for ($i = 0; $i < 5; $i++) {
            $this->mock->append(new \GuzzleHttp\Psr7\Response(200, [], $responseBody));
        }

        // Suppress output from code samples
        ob_start();

        $client = $this->client;

        $instalment_schedule = $client->instalmentSchedules()->createWithDates([
            "params" => [
                "name" => "ACME Invoice 103",
                "total_amount" => 10000, // 100 GBP in pence, collected from the customer
                "app_fee" => 10, // Your 10 pence fee, applied to each instalment,
                                 // to be paid out to you
                "currency" => 'GBP',
                "instalments" => [
                    [
                        "charge_date" => '2019-08-20',
                        "amount" => 3400
                    ],
                    [
                        "charge_date" => '2019-09-03',
                        "amount" => 3400
                    ],
                    [
                        "charge_date" => '2019-09-17',
                        "amount" => 3200
                    ],
                  ],
                  "links" => [
                      "mandate" => 'MD0000XH9A3T4C'
                  ],
                  "metadata" => []
              ],
              "headers" => [
                  'Idempotency-Key' => 'random_instalment_schedule_specific_string'
            ]
        ]);

        ob_end_clean();
    }




    public function testCreateWithScheduleCodeSample()
    {
        $this->expectNotToPerformAssertions();

        // Mock response - enqueue multiple times to handle code samples with multiple API calls
        $responseBody = '{ "instalment_schedules": {} }';
        for ($i = 0; $i < 5; $i++) {
            $this->mock->append(new \GuzzleHttp\Psr7\Response(200, [], $responseBody));
        }

        // Suppress output from code samples
        ob_start();

        $client = $this->client;

        $instalment_schedule = $client->instalmentSchedules()->createWithSchedule([
            "params" => [
                "name" => "ACME Invoice 103",
                "total_amount" => 10000, // 100 GBP in pence, collected from the customer
                "app_fee" => 10, // Your 10 pence fee, applied to each instalment,
                                 // to be paid out to you
                "currency" => "GBP",
                "instalments" => [
                    "start_date" => "2019-08-20",
                    "interval_unit" => "weekly",
                    "interval" => 2,
                    "amounts" => [
                        3400,
                        3400,
                        3200
                    ]
                ],
                "links" => [
                    "mandate" => "MD0000XH9A3T4C"
                ],
                "metadata" => []
            ],
            "headers" => [
                "Idempotency-Key" => "random_instalment_schedule_specific_string"
            ]
        ]);

        ob_end_clean();
    }




    public function testListCodeSample()
    {
        $this->expectNotToPerformAssertions();

        // Mock response - enqueue multiple times to handle code samples with multiple API calls
        $responseBody = '{ "instalment_schedules": [{}], "meta": { "cursors": {}, "limit": 50 } }';
        for ($i = 0; $i < 5; $i++) {
            $this->mock->append(new \GuzzleHttp\Psr7\Response(200, [], $responseBody));
        }

        // Suppress output from code samples
        ob_start();

        $client = $this->client;

        $client->instalmentSchedules()->list();

        $client->instalmentSchedules()->list([
          "params" => ["created_at[gt]" => "2015-11-03T09:30:00Z"]
        ]);

        ob_end_clean();
    }




    public function testGetCodeSample()
    {
        $this->expectNotToPerformAssertions();

        // Mock response - enqueue multiple times to handle code samples with multiple API calls
        $responseBody = '{ "instalment_schedules": {} }';
        for ($i = 0; $i < 5; $i++) {
            $this->mock->append(new \GuzzleHttp\Psr7\Response(200, [], $responseBody));
        }

        // Suppress output from code samples
        ob_start();

        $client = $this->client;

        $client->instalmentSchedules()->get("IS123");

        ob_end_clean();
    }




    public function testUpdateCodeSample()
    {
        $this->expectNotToPerformAssertions();

        // Mock response - enqueue multiple times to handle code samples with multiple API calls
        $responseBody = '{ "instalment_schedules": {} }';
        for ($i = 0; $i < 5; $i++) {
            $this->mock->append(new \GuzzleHttp\Psr7\Response(200, [], $responseBody));
        }

        // Suppress output from code samples
        ob_start();

        $client = $this->client;

        $client->instalmentSchedules()->update("IS123", [
          "params" => ["metadata" => ["key" => "value"]]
        ]);

        ob_end_clean();
    }




    public function testCancelCodeSample()
    {
        $this->expectNotToPerformAssertions();

        // Mock response - enqueue multiple times to handle code samples with multiple API calls
        $responseBody = '{ "instalment_schedules": {} }';
        for ($i = 0; $i < 5; $i++) {
            $this->mock->append(new \GuzzleHttp\Psr7\Response(200, [], $responseBody));
        }

        // Suppress output from code samples
        ob_start();

        $client = $this->client;

        $client->instalmentSchedules()->cancel("IS123");

        ob_end_clean();
    }
}
