<?php

//
// WARNING: Do not edit by hand, this file was generated by Crank:
// https://github.com/gocardless/crank
//

// Code Sample Tests
// These tests verify that the documentation code samples are syntactically valid
// and can execute against a mocked API without errors.
//
// IMPORTANT: These tests do NOT verify business logic - they only verify that
// the code samples compile and execute without syntax errors.

namespace GoCardlessPro\CodeSamples;

use PHPUnit\Framework\TestCase;
use GoCardlessPro\Environment;

class MandateImportEntriesCodeSamplesTest extends TestCase
{
    protected $mock;
    protected $client;

    public function setUp(): void
    {
        parent::setUp();
        $this->mock = new \GuzzleHttp\Handler\MockHandler([]);
        $handler = \GuzzleHttp\HandlerStack::create($this->mock);

        $mock_http_client = new \GuzzleHttp\Client([
            'handler' => $handler,
            'http_errors' => false
        ]);
        $this->client = new \GoCardlessPro\Client(
            array(
                'access_token' => 'SECRET_TOKEN',
                'environment' => Environment::LIVE,
                'http_client' => $mock_http_client
            )
        );
    }






    public function testCreateCodeSample()
    {
        $this->expectNotToPerformAssertions();

        // Mock response - enqueue multiple times to handle code samples with multiple API calls
        $responseBody = '{ "mandate_import_entries": {} }';
        for ($i = 0; $i < 5; $i++) {
            $this->mock->append(new \GuzzleHttp\Psr7\Response(200, [], $responseBody));
        }

        // Suppress output from code samples
        ob_start();

        $client = $this->client;

        $client->mandateImportEntries()->create([
          "params" => [
            "links" => [
              "mandate_import" => "IM000010790WX1"
            ],
            "record_identifier" => "bank-file.xml/line-1",
            "customer" => [
              "company_name" => "Jane's widgets",
              "email" => "jane@janeswidgets.fr"
            ],
            "bank_account" => [
              "account_holder_name" => "Jane Doe",
              "iban" => "FR14BARC20000055779911"
            ],
            "amendment" => [
              "original_mandate_reference" => "REFNMANDATE",
              "original_creditor_id" => "FR123OTHERBANK",
              "original_creditor_name" => "Existing DD Provider"
            ]
          ]
        ]);

        ob_end_clean();
    }




    public function testListCodeSample()
    {
        $this->expectNotToPerformAssertions();

        // Mock response - enqueue multiple times to handle code samples with multiple API calls
        $responseBody = '{ "mandate_import_entries": [{}], "meta": { "cursors": {}, "limit": 50 } }';
        for ($i = 0; $i < 5; $i++) {
            $this->mock->append(new \GuzzleHttp\Psr7\Response(200, [], $responseBody));
        }

        // Suppress output from code samples
        ob_start();

        $client = $this->client;

        $client->mandateImportEntries()->all([
          "params" => ["mandate_import" => "IM000010790WX1"]
        ]);

        ob_end_clean();
    }
}
