<?php

//
// WARNING: Do not edit by hand, this file was generated by Crank:
// https://github.com/gocardless/crank
//

// Code Sample Tests
// These tests verify that the documentation code samples are syntactically valid
// and can execute against a mocked API without errors.
//
// IMPORTANT: These tests do NOT verify business logic - they only verify that
// the code samples compile and execute without syntax errors.

namespace GoCardlessPro\CodeSamples;

use PHPUnit\Framework\TestCase;
use GoCardlessPro\Environment;

class PayerThemesCodeSamplesTest extends TestCase
{
    protected $mock;
    protected $client;

    public function setUp(): void
    {
        parent::setUp();
        $this->mock = new \GuzzleHttp\Handler\MockHandler([]);
        $handler = \GuzzleHttp\HandlerStack::create($this->mock);

        $mock_http_client = new \GuzzleHttp\Client([
            'handler' => $handler,
            'http_errors' => false
        ]);
        $this->client = new \GoCardlessPro\Client(
            array(
                'access_token' => 'SECRET_TOKEN',
                'environment' => Environment::LIVE,
                'http_client' => $mock_http_client
            )
        );
    }






    public function testCreateForCreditorCodeSample()
    {
        $this->expectNotToPerformAssertions();

        // Mock response - enqueue multiple times to handle code samples with multiple API calls
        $responseBody = '{ "payer_themes": {} }';
        for ($i = 0; $i < 5; $i++) {
            $this->mock->append(new \GuzzleHttp\Psr7\Response(200, [], $responseBody));
        }

        // Suppress output from code samples
        ob_start();

        $client = $this->client;

        $client->payerThemes()->createForCreditor([
          "params" => [
            "header_background_colour" => "#BD10E0",
            "link_text_colour" => "#7ED321",
            "button_background_colour" => "#128DAA",
            "content_box_border_colour" => "#BD10E0",
            "links" => [
              "creditor" => "CR123"
            ]
          ]
        ]);

        ob_end_clean();
    }
}
