<?php
/**
 * WARNING: Do not edit by hand, this file was generated by Crank:
 *
 * https://github.com/gocardless/crank
 */

namespace GoCardlessPro\Services;

use \GoCardlessPro\Core\Paginator;
use \GoCardlessPro\Core\Util;
use \GoCardlessPro\Core\ListResponse;
use \GoCardlessPro\Resources\Balance;
use \GoCardlessPro\Core\Exception\InvalidStateException;


/**
 * Service that provides access to the Balance
 * endpoints of the API
 *
 * @method ListResponse list(array $params)
 */
class BalancesService extends BaseService
{

    protected $envelope_key   = 'balances';
    protected $resource_class = '\GoCardlessPro\Resources\Balance';


    /**
     * List balances
     *
     * Example URL: /balances
     *
     * @param  array<string, mixed> $params An associative array for any params
     * @return ListResponse
     **/
    protected function _doList($params = array())
    {
        $path = "/balances";
        if(isset($params['params'])) { $params['query'] = $params['params'];
            unset($params['params']);
        }

        
        $response = $this->api_client->get($path, $params);
        

        return $this->getResourceForResponse($response);
    }

    /**
     * List balances
     *
     * Example URL: /balances
     *
     * @param  string[mixed] $params
     * @return Paginator
     **/
    public function all($params = array())
    {
        return new Paginator($this, $params);
    }

}
