<?php
/**
 * WARNING: Do not edit by hand, this file was generated by Crank:
 *
 * https://github.com/gocardless/crank
 */

namespace GoCardlessPro\Services;

use \GoCardlessPro\Core\Paginator;
use \GoCardlessPro\Core\Util;
use \GoCardlessPro\Core\ListResponse;
use \GoCardlessPro\Resources\SchemeIdentifier;
use \GoCardlessPro\Core\Exception\InvalidStateException;


/**
 * Service that provides access to the SchemeIdentifier
 * endpoints of the API
 *
 * @method ListResponse list(array $params)
 */
class SchemeIdentifiersService extends BaseService
{

    protected $envelope_key   = 'scheme_identifiers';
    protected $resource_class = '\GoCardlessPro\Resources\SchemeIdentifier';


    /**
     * Create a scheme identifier
     *
     * Example URL: /scheme_identifiers
     *
     * @param  array<string, mixed> $params An associative array for any params
     * @return SchemeIdentifier
     **/
    public function create($params = array())
    {
        $path = "/scheme_identifiers";
        if(isset($params['params'])) { 
            $params['body'] = json_encode(array($this->envelope_key => (object)$params['params']));
        
            unset($params['params']);
        }

        
        try {
            $response = $this->api_client->post($path, $params);
        } catch(InvalidStateException $e) {
            if ($e->isIdempotentCreationConflict()) {
                if ($this->api_client->error_on_idempotency_conflict) {
                    throw $e;
                }
                return $this->get($e->getConflictingResourceId());
            }

            throw $e;
        }
        

        return $this->getResourceForResponse($response);
    }

    /**
     * List scheme identifiers
     *
     * Example URL: /scheme_identifiers
     *
     * @param  array<string, mixed> $params An associative array for any params
     * @return ListResponse
     **/
    protected function _doList($params = array())
    {
        $path = "/scheme_identifiers";
        if(isset($params['params'])) { $params['query'] = $params['params'];
            unset($params['params']);
        }

        
        $response = $this->api_client->get($path, $params);
        

        return $this->getResourceForResponse($response);
    }

    /**
     * Get a single scheme identifier
     *
     * Example URL: /scheme_identifiers/:identity
     *
     * @param  string        $identity Unique identifier, usually beginning with "SU".
     * @param  array<string, mixed> $params   An associative array for any params
     * @return SchemeIdentifier
     **/
    public function get($identity, $params = array())
    {
        $path = Util::subUrl(
            '/scheme_identifiers/:identity',
            array(
                
                'identity' => $identity
            )
        );
        if(isset($params['params'])) { $params['query'] = $params['params'];
            unset($params['params']);
        }

        
        $response = $this->api_client->get($path, $params);
        

        return $this->getResourceForResponse($response);
    }

    /**
     * List scheme identifiers
     *
     * Example URL: /scheme_identifiers
     *
     * @param  array<string, mixed> $params
     * @return Paginator
     **/
    public function all($params = array())
    {
        return new Paginator($this, $params);
    }

}
