<?php

/**
 * WARNING: Do not edit by hand, this file was generated by Crank:
 *
 * https://github.com/gocardless/crank
 */

namespace GoCardlessPro\Resources;

/**
 * A thin wrapper around a balance, providing access to its
 * attributes
 *
 * @property-read mixed $amount
 * @property-read mixed $balance_type
 * @property-read mixed $currency
 * @property-read mixed $last_updated_at
 * @property-read mixed $links
 */
class Balance extends BaseResource
{
    protected $model_name = "Balance";

    /**
     * The total amount in the balance, defined as the sum of all debits
     * subtracted from the sum of all credits,
     * in the lowest denomination for the currency (e.g. pence in GBP, cents in
     * EUR).
     */
    protected $amount;

    /**
     * Type of the balance. Could be one of
     *
     * - `pending_payments_submitted`: Payments we have submitted to the scheme
     * but not yet confirmed. This does not exactly correspond to Pending
     * payments in the dashboard, because this balance does not include payments
     * that are pending submission.
     * - `confirmed_funds`: Payments that have been confirmed minus fees and
     * unclaimed debits for refunds, failures and chargebacks. These funds have
     * not yet been moved into a payout.
     * - `pending_payouts`: Confirmed payments that have been moved into a
     * payout. This is the total due to be paid into your bank account in the
     * next payout run (payouts happen once every business day).
     * `pending_payouts` will only be non-zero while we are generating and
     * submitting the payouts to our partner bank.
     */
    protected $balance_type;

    /**
     * ISO 4217 (https://en.wikipedia.org/wiki/ISO_4217#Active_codes) currency
     * code. Currently "AUD", "CAD", "DKK", "EUR", "GBP", "NZD", "SEK" and "USD"
     * are supported.
     */
    protected $currency;

    /**
     * Dynamic timestamp
     * (https://developer.gocardless.com/api-reference/#api-usage-dates-and-times)
     * recording when this resource was last updated.
     */
    protected $last_updated_at;

    /**
     *
     */
    protected $links;
}
