<?php

/**
 * WARNING: Do not edit by hand, this file was generated by Crank:
 *
 * https://github.com/gocardless/crank
 */

namespace GoCardlessPro\Resources;

/**
 * A thin wrapper around a bank_details_lookup, providing access to its
 * attributes
 *
 * @property-read mixed $available_debit_schemes
 * @property-read mixed $bank_name
 * @property-read mixed $bic
 * @property-read mixed $payer_name_verification_result
 */
class BankDetailsLookup extends BaseResource
{
    protected $model_name = "BankDetailsLookup";

    /**
     * Array of <a
     * href="https://developer.gocardless.com/api-reference/#mandates_scheme">schemes</a>
     * supported for this bank account. This will be an empty array if the bank
     * account is not reachable by any schemes.
     */
    protected $available_debit_schemes;

    /**
     * The name of the bank with which the account is held (if available).
     */
    protected $bank_name;

    /**
     * ISO 9362 SWIFT BIC of the bank with which the account is held.
     *
     * <p class="notice">Even if no BIC is returned for an account, GoCardless
     * may still be able to collect payments from it - you should refer to the
     * <code>available_debit_schemes</code> attribute to determine
     * reachability.</p>
     */
    protected $bic;

    /**
     * The result of the payer name verification check performed during the
     * lookup. <code>null</code> if no check was performed.
     *
     * <ul>
     * <li><code>full</code>: The name provided matches the name held by the
     * bank.</li>
     * <li><code>close</code>: The name provided is a close but not exact match
     * to the name held by the bank.</li>
     * <li><code>cannot_perform_verification</code>: A verification was
     * attempted but could not be completed. This can happen for a number of
     * reasons, including the account holder's bank not participating in the
     * verification scheme, the account not being eligible for verification
     * (e.g. the account holder has opted out), or the bank details not being
     * resolvable, among others.</li>
     * <li><code>null</code>: Verification was not triggered. Either PNV is not
     * supported for the scheme, or PNV feature is disabled for your
     * organisation.</li>
     * </ul>
     */
    protected $payer_name_verification_result;
}
