<?php

/**
 * WARNING: Do not edit by hand, this file was generated by Crank:
 *
 * https://github.com/gocardless/crank
 */

namespace GoCardlessPro\Resources;

/**
 * A thin wrapper around a creditor, providing access to its
 * attributes
 *
 * @property-read mixed $address_line1
 * @property-read mixed $address_line2
 * @property-read mixed $address_line3
 * @property-read mixed $bank_reference_prefix
 * @property-read mixed $can_create_refunds
 * @property-read mixed $city
 * @property-read mixed $country_code
 * @property-read mixed $created_at
 * @property-read mixed $creditor_type
 * @property-read mixed $custom_payment_pages_enabled
 * @property-read mixed $fx_payout_currency
 * @property-read mixed $id
 * @property-read mixed $links
 * @property-read mixed $logo_url
 * @property-read mixed $mandate_imports_enabled
 * @property-read mixed $merchant_responsible_for_notifications
 * @property-read mixed $name
 * @property-read mixed $postal_code
 * @property-read mixed $region
 * @property-read mixed $scheme_identifiers
 * @property-read mixed $verification_status
 */
class Creditor extends BaseResource
{
    protected $model_name = "Creditor";

    /**
     * The first line of the creditor's address.
     */
    protected $address_line1;

    /**
     * The second line of the creditor's address.
     */
    protected $address_line2;

    /**
     * The third line of the creditor's address.
     */
    protected $address_line3;

    /**
     * Prefix for the bank reference of payouts sent to this creditor. For
     * instance, if
     * the creditor's <code>bank_reference_prefix</code> was <code>ACME</code>,
     * the bank reference of a payout
     * sent to that creditor could be <code>ACME-8G7Q8</code>.
     *
     * This prefix is also used for refunds in EUR and GBP.
     */
    protected $bank_reference_prefix;

    /**
     * Boolean indicating whether the creditor is permitted to create refunds.
     */
    protected $can_create_refunds;

    /**
     * The city of the creditor's address.
     */
    protected $city;

    /**
     * <a
     * href="https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements">ISO
     * 3166-1 alpha-2 code.</a>
     */
    protected $country_code;

    /**
     * Fixed <a
     * href="https://developer.gocardless.com/api-reference/#api-usage-dates-and-times">timestamp</a>,
     * recording when this resource was created.
     */
    protected $created_at;

    /**
     * The type of business of the creditor. Currently, <code>individual</code>,
     * <code>company</code>, <code>charity</code>, <code>partnership</code>, and
     * <code>trust</code> are supported.
     */
    protected $creditor_type;

    /**
     * Boolean value indicating whether creditor has the <a
     * href="https://hub.gocardless.com/s/article/Custom-payment-pages">Custom
     * Payment Pages</a> functionality enabled.
     */
    protected $custom_payment_pages_enabled;

    /**
     * <a href="https://en.wikipedia.org/wiki/ISO_4217#Active_codes">ISO
     * 4217</a> code for the currency in which amounts will be paid out (after
     * foreign exchange). Currently "AUD", "CAD", "DKK", "EUR", "GBP", "NZD",
     * "SEK" and "USD" are supported. Present only if payouts will be (or were)
     * made via foreign exchange.
     */
    protected $fx_payout_currency;

    /**
     * Unique identifier, beginning with "CR".
     */
    protected $id;

    /**
     *
     */
    protected $links;

    /**
     * URL for the creditor's logo, which may be shown on their payment pages.
     */
    protected $logo_url;

    /**
     * Boolean value indicating whether creditor has the <a
     * href="https://developer.gocardless.com/api-reference/#core-endpoints-mandate-imports">Mandate
     * Imports</a> functionality enabled.
     */
    protected $mandate_imports_enabled;

    /**
     * Boolean value indicating whether the organisation is responsible for
     * sending all customer notifications (note this is separate from the
     * functionality described <a
     * href="https://developer.gocardless.com/getting-started/api/handling-customer-notifications/">here</a>).
     * If you are a partner app, and this value is true, you should not send
     * notifications on behalf of this organisation.
     */
    protected $merchant_responsible_for_notifications;

    /**
     * The creditor's trading name.
     */
    protected $name;

    /**
     * The creditor's postal code.
     */
    protected $postal_code;

    /**
     * The creditor's address region, county or department.
     */
    protected $region;

    /**
     * An array of the scheme identifiers this creditor can create mandates
     * against.
     *
     * The support address, <code>phone_number</code> and <code>email</code>
     * fields are for customers to contact the merchant for support purposes.
     * They must be displayed on the payment page, please see our <a
     * href="https://developer.gocardless.com/api-reference/#appendix-compliance-requirements">compliance
     * requirements</a> for more details.
     */
    protected $scheme_identifiers;

    /**
     * The creditor's verification status, indicating whether they can yet
     * receive payouts. For more details on handling verification as a partner,
     * see our <a
     * href="https://developer.gocardless.com/getting-started/partners/helping-your-users-get-verified/">"Helping
     * your users get verified" guide</a>. One of:
     *
     * <ul>
     * <li><code>successful</code>: The creditor's account is fully verified,
     * and they can receive payouts. Once a creditor has been successfully
     * verified, they may in the future require further verification - for
     * example, if they change their payout bank account, we will have to check
     * that they own the new bank account before they can receive payouts
     * again.</li>
     * <li><code>in_review</code>: The creditor has provided all of the
     * information currently requested, and it is awaiting review by GoCardless
     * before they can be verified and receive payouts.</li>
     * <li><code>action_required</code>: The creditor needs to provide further
     * information to verify their account so they can receive payouts, and
     * should visit the verification flow.</li>
     * </ul>
     */
    protected $verification_status;
}
