<?php

/**
 * WARNING: Do not edit by hand, this file was generated by Crank:
 *
 * https://github.com/gocardless/crank
 */

namespace GoCardlessPro\Resources;

/**
 * A thin wrapper around a event, providing access to its
 * attributes
 *
 * @property-read mixed $action
 * @property-read mixed $created_at
 * @property-read mixed $customer_notifications
 * @property-read mixed $details
 * @property-read mixed $id
 * @property-read mixed $links
 * @property-read mixed $metadata
 * @property-read mixed $resource_metadata
 * @property-read mixed $resource_type
 * @property-read mixed $source
 */
class Event extends BaseResource
{
    protected $model_name = "Event";

    /**
     * What has happened to the resource. See <a
     * href="https://developer.gocardless.com/api-reference/#event-types">Event
     * Types</a> for the possible actions.
     */
    protected $action;

    /**
     * Fixed <a
     * href="https://developer.gocardless.com/api-reference/#api-usage-dates-and-times">timestamp</a>,
     * recording when this resource was created.
     */
    protected $created_at;

    /**
     * Present only in webhooks when an integrator is authorised to send their
     * own
     * notifications. See <a
     * href="https://developer.gocardless.com/getting-started/api/handling-customer-notifications/">here</a>
     * for further information.
     */
    protected $customer_notifications;

    /**
     *
     */
    protected $details;

    /**
     * Unique identifier, beginning with "EV".
     */
    protected $id;

    /**
     *
     */
    protected $links;

    /**
     * The metadata that was passed when making the API request that triggered
     * the event
     * (for instance, cancelling a mandate).
     *
     * This field will only be populated if the <code>details[origin]</code>
     * field is <code>api</code> otherwise it will be an empty object.
     */
    protected $metadata;

    /**
     * The metadata of the resource that the event is for. For example, this
     * field will have the same
     * value of the <code>mandate[metadata]</code> field on the response you
     * would receive from performing a GET request on a mandate.
     */
    protected $resource_metadata;

    /**
     * The resource type for this event. One of:
     *
     * <ul>
     * <li><code>billing_requests</code></li>
     * <li><code>creditors</code></li>
     * <li><code>exports</code></li>
     * <li><code>instalment_schedules</code></li>
     * <li><code>mandates</code></li>
     * <li><code>payer_authorisations</code></li>
     * <li><code>payments</code></li>
     * <li><code>payouts</code></li>
     * <li><code>refunds</code></li>
     * <li><code>scheme_identifiers</code></li>
     * <li><code>subscriptions</code></li>
     * <li><code>outbound_payments</code></li>
     * <li><code>payment_account_transactions</code></li>
     * </ul>
     */
    protected $resource_type;

    /**
     * Audit information about the source of the event.
     */
    protected $source;
}
