<?php

/**
 * WARNING: Do not edit by hand, this file was generated by Crank:
 *
 * https://github.com/gocardless/crank
 */

namespace GoCardlessPro\Resources;

/**
 * A thin wrapper around a funds_availability, providing access to its
 * attributes
 *
 * @property-read mixed $available
 */
class FundsAvailability extends BaseResource
{
    protected $model_name = "FundsAvailability";

    /**
     *  Indicates if the amount is available
     */
    protected $available;
}
