<?php

/**
 * WARNING: Do not edit by hand, this file was generated by Crank:
 *
 * https://github.com/gocardless/crank
 */

namespace GoCardlessPro\Resources;

/**
 * A thin wrapper around a institution, providing access to its
 * attributes
 *
 * @property-read mixed $country_code
 * @property-read mixed $icon_url
 * @property-read mixed $id
 * @property-read mixed $limits
 * @property-read mixed $logo_url
 * @property-read mixed $name
 * @property-read mixed $roles
 */
class Institution extends BaseResource
{
    protected $model_name = "Institution";

    /**
     * <a
     * href="https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements">ISO
     * 3166-1</a> alpha-2 code. The country code of the institution. If nothing
     * is provided, institutions with the country code 'GB' are returned by
     * default.
     */
    protected $country_code;

    /**
     * A URL pointing to the icon for this institution
     */
    protected $icon_url;

    /**
     * The unique identifier for this institution
     */
    protected $id;

    /**
     * Defines individual limits for business and personal accounts.
     */
    protected $limits;

    /**
     * A URL pointing to the logo for this institution
     */
    protected $logo_url;

    /**
     * A human readable name for this institution
     */
    protected $name;

    /**
     * The roles assigned to this institution, representing the open banking
     * features it supports.
     */
    protected $roles;
}
