<?php

/**
 * WARNING: Do not edit by hand, this file was generated by Crank:
 *
 * https://github.com/gocardless/crank
 */

namespace GoCardlessPro\Resources;

/**
 * A thin wrapper around a logo, providing access to its
 * attributes
 *
 * @property-read mixed $id
 */
class Logo extends BaseResource
{
    protected $model_name = "Logo";

    /**
     * Unique identifier, beginning with "LO".
     */
    protected $id;
}
