<?php
/**
 * WARNING: Do not edit by hand, this file was generated by Crank:
 *
 * https://github.com/gocardless/crank
 */

namespace GoCardlessPro\Resources;

/**
 * A thin wrapper around a mandate_import_entry, providing access to its
 * attributes
 *
 * @property-read mixed $created_at
 * @property-read mixed $links
 * @property-read mixed $processing_errors
 * @property-read mixed $record_identifier
 */
class MandateImportEntry extends BaseResource
{
    protected $model_name = "MandateImportEntry";

    /**
     * Fixed [timestamp](#api-usage-dates-and-times), recording when this
     * resource was created.
     */
    protected $created_at;

    /**
     * Related resources
     */
    protected $links;

    /**
     * Per-resource processing errors
     */
    protected $processing_errors;

    /**
     * A unique identifier for this entry, which you can use (once the import
     * has been
     * processed by GoCardless) to identify the records that have been created.
     * Limited
     * to 255 characters.
     */
    protected $record_identifier;

}
