<?php
/**
 * WARNING: Do not edit by hand, this file was generated by Crank:
 *
 * https://github.com/gocardless/crank
 */

namespace GoCardlessPro\Resources;

/**
 * A thin wrapper around a mandate_request_constraints, providing access to its
 * attributes
 *
 * @property-read $end_date
 * @property-read $max_amount_per_payment
 * @property-read $periodic_limits
 * @property-read $start_date
 */
class MandateRequestConstraints extends BaseResource
{
    protected $model_name = "MandateRequestConstraints";

    /**
     * The latest date at which payments can be taken, must occur after
     * start_date if present
     */
    protected $end_date;

    /**
     * The maximum amount that can be charged for a single payment
     */
    protected $max_amount_per_payment;

    /**
     * List of periodic limits and constraints which apply to them
     */
    protected $periodic_limits;

    /**
     * The date from which payments can be taken
     */
    protected $start_date;

}
