<?php

/**
 * WARNING: Do not edit by hand, this file was generated by Crank:
 *
 * https://github.com/gocardless/crank
 */

namespace GoCardlessPro\Resources;

/**
 * A thin wrapper around a mandate_import, providing access to its
 * attributes
 *
 * @property-read mixed $created_at
 * @property-read mixed $id
 * @property-read mixed $links
 * @property-read mixed $scheme
 * @property-read mixed $status
 */
class MandateImport extends BaseResource
{
    protected $model_name = "MandateImport";

    /**
     * Fixed <a
     * href="https://developer.gocardless.com/api-reference/#api-usage-dates-and-times">timestamp</a>,
     * recording when this resource was created.
     */
    protected $created_at;

    /**
     * Unique identifier, beginning with "IM".
     */
    protected $id;

    /**
     * Related resources
     */
    protected $links;

    /**
     * The scheme of the mandates to be imported.<br></br>All mandates in a
     * single mandate
     * import must be for the same scheme.
     */
    protected $scheme;

    /**
     * The status of the mandate import.
     *
     * <ul>
     * <li><code>created</code>: A new mandate import.</li>
     * <li><code>submitted</code>: After the integrator has finished adding
     * mandates and <a
     * href="https://developer.gocardless.com/api-reference/#mandate-imports-submit-a-mandate-import">submitted</a>
     * the import.</li>
     * <li><code>cancelled</code>: If the integrator <a
     * href="https://developer.gocardless.com/api-reference/#mandate-imports-cancel-a-mandate-import">cancelled</a>
     * the mandate import.</li>
     * <li><code>processing</code>: Once a mandate import has been approved by a
     * GoCardless team member it will be in this state while mandates are
     * imported.</li>
     * <li><code>processed</code>: When all mandates have been imported
     * successfully.</li>
     * </ul>
     */
    protected $status;
}
