<?php

/**
 * WARNING: Do not edit by hand, this file was generated by Crank:
 *
 * https://github.com/gocardless/crank
 */

namespace GoCardlessPro\Resources;

/**
 * A thin wrapper around a negative_balance_limit, providing access to its
 * attributes
 *
 * @property-read mixed $balance_limit
 * @property-read mixed $created_at
 * @property-read mixed $currency
 * @property-read mixed $id
 * @property-read mixed $links
 */
class NegativeBalanceLimit extends BaseResource
{
    protected $model_name = "NegativeBalanceLimit";

    /**
     * The limit amount in pence (e.g. 10000 for a -100 GBP limit).
     */
    protected $balance_limit;

    /**
     * Fixed <a
     * href="https://developer.gocardless.com/api-reference/#api-usage-dates-and-times">timestamp</a>,
     * recording when this limit was created.
     */
    protected $created_at;

    /**
     * <a href="https://en.wikipedia.org/wiki/ISO_4217#Active_codes">ISO
     * 4217</a> currency code. Currently "AUD", "CAD", "DKK", "EUR", "GBP",
     * "NZD", "SEK" and "USD" are supported.
     */
    protected $currency;

    /**
     * Unique identifier, beginning with "NBL".
     */
    protected $id;

    /**
     *
     */
    protected $links;
}
