<?php
/**
 * WARNING: Do not edit by hand, this file was generated by Crank:
 *
 * https://github.com/gocardless/crank
 */

namespace GoCardlessPro\Resources;

/**
 * A thin wrapper around a negative_balance_limit, providing access to its
 * attributes
 *
 * @property-read $active
 * @property-read $balance_limit
 * @property-read $created_at
 * @property-read $currency
 * @property-read $id
 * @property-read $links
 * @property-read $reason
 * @property-read $updated_at
 */
class NegativeBalanceLimit extends BaseResource
{
    protected $model_name = "NegativeBalanceLimit";

    /**
     * Whether or not this limit is currently active
     */
    protected $active;

    /**
     * The limit amount in pence (e.g. 10000 for a -100 GBP limit).
     */
    protected $balance_limit;

    /**
     * Fixed [timestamp](#api-usage-time-zones--dates), recording when this
     * limit was created.
     */
    protected $created_at;

    /**
     * [ISO 4217](http://en.wikipedia.org/wiki/ISO_4217#Active_codes) currency
     * code. Currently "AUD", "CAD", "DKK", "EUR", "GBP", "NZD", "SEK" and "USD"
     * are supported.
     */
    protected $currency;

    /**
     * Unique identifier, beginning with "NBL".
     */
    protected $id;

    /**
     * 
     */
    protected $links;

    /**
     * the reason this limit was created
     */
    protected $reason;

    /**
     * Fixed [timestamp](#api-usage-time-zones--dates), recording when this
     * limit was last updated.
     */
    protected $updated_at;

}
