<?php

/**
 * WARNING: Do not edit by hand, this file was generated by Crank:
 *
 * https://github.com/gocardless/crank
 */

namespace GoCardlessPro\Resources;

/**
 * A thin wrapper around a outbound_payment_import, providing access to its
 * attributes
 *
 * @property-read mixed $amount_sum
 * @property-read mixed $authorisation_url
 * @property-read mixed $created_at
 * @property-read mixed $currency
 * @property-read mixed $entry_counts
 * @property-read mixed $id
 * @property-read mixed $links
 * @property-read mixed $status
 */
class OutboundPaymentImport extends BaseResource
{
    protected $model_name = "OutboundPaymentImport";

    /**
     * The sum of all import entry amounts, in the lowest denomination for the
     * currency (e.g. pence in GBP, cents in EUR).
     */
    protected $amount_sum;

    /**
     * The link to the GoCardless dashboard to review and authorise the import
     */
    protected $authorisation_url;

    /**
     * Fixed <a
     * href="https://developer.gocardless.com/api-reference/#api-usage-dates-and-times">timestamp</a>,
     * recording when this resource was created.
     */
    protected $created_at;

    /**
     * <a href="https://en.wikipedia.org/wiki/ISO_4217#Active_codes">ISO
     * 4217</a> currency. Currently only "GBP" is supported.
     */
    protected $currency;

    /**
     *
     */
    protected $entry_counts;

    /**
     * Unique identifier, beginning with "IM".
     */
    protected $id;

    /**
     *
     */
    protected $links;

    /**
     * The status of the outbound payment import.
     *
     * <ul>
     * <li><code>created</code>: The initial state of a new import.</li>
     * <li><code>validating</code>: Import validation in progress.</li>
     * <li><code>invalid</code>: Import validation failed.</li>
     * <li><code>valid</code>: Import validation succeeded.</li>
     * <li><code>processing</code>: Authorisation received; payments are being
     * generated.</li>
     * <li><code>processed</code>: All entries have been successfully converted
     * into outbound payments.</li>
     * <li><code>cancelled</code>: The import was cancelled by a user or
     * automatically expired by the system.</li>
     * </ul>
     */
    protected $status;
}
