<?php

/**
 * WARNING: Do not edit by hand, this file was generated by Crank:
 *
 * https://github.com/gocardless/crank
 */

namespace GoCardlessPro\Resources;

/**
 * A thin wrapper around a outbound_payment_import_entry, providing access to its
 * attributes
 *
 * @property-read mixed $amount
 * @property-read mixed $created_at
 * @property-read mixed $id
 * @property-read mixed $links
 * @property-read mixed $metadata
 * @property-read mixed $processed_at
 * @property-read mixed $reference
 * @property-read mixed $scheme
 * @property-read mixed $validation_errors
 * @property-read mixed $verification_result
 */
class OutboundPaymentImportEntry extends BaseResource
{
    protected $model_name = "OutboundPaymentImportEntry";

    /**
     * Amount, in the lowest denomination for the currency (e.g. pence in GBP,
     * cents in EUR).
     */
    protected $amount;

    /**
     * Fixed [timestamp](#api-usage-dates-and-times), recording when this
     * resource was created.
     */
    protected $created_at;

    /**
     * Unique identifier, beginning with "IE".
     */
    protected $id;

    /**
     *
     */
    protected $links;

    /**
     * Key-value store of custom data. Up to 3 keys are permitted, with
     * key names up to 50 characters and values up to 500 characters.
     */
    protected $metadata;

    /**
     * Fixed [timestamp](#api-usage-dates-and-times), recording when this entry
     * was processed.
     */
    protected $processed_at;

    /**
     * An optional reference for the outbound payment.
     */
    protected $reference;

    /**
     * Bank payment scheme to process the outbound payment. Currently only
     * "faster_payments" (GBP) is supported.
     */
    protected $scheme;

    /**
     * Per-field validation errors for this entry, keyed by resource type and
     * then by field name.
     */
    protected $validation_errors;

    /**
     * The result of bank account holder verification, if performed.
     */
    protected $verification_result;
}
