<?php

/**
 * WARNING: Do not edit by hand, this file was generated by Crank:
 *
 * https://github.com/gocardless/crank
 */

namespace GoCardlessPro\Resources;

/**
 * A thin wrapper around a payer_theme, providing access to its
 * attributes
 *
 * @property-read mixed $id
 */
class PayerTheme extends BaseResource
{
    protected $model_name = "PayerTheme";

    /**
     *  Unique identifier, beginning with "PTH".
     */
    protected $id;
}
