<?php

/**
 * WARNING: Do not edit by hand, this file was generated by Crank:
 *
 * https://github.com/gocardless/crank
 */

namespace GoCardlessPro\Resources;

/**
 * A thin wrapper around a payout, providing access to its
 * attributes
 *
 * @property-read mixed $amount
 * @property-read mixed $arrival_date
 * @property-read mixed $created_at
 * @property-read mixed $currency
 * @property-read mixed $deducted_fees
 * @property-read mixed $fx
 * @property-read mixed $id
 * @property-read mixed $links
 * @property-read mixed $metadata
 * @property-read mixed $payout_type
 * @property-read mixed $reference
 * @property-read mixed $status
 * @property-read mixed $tax_currency
 */
class Payout extends BaseResource
{
    protected $model_name = "Payout";

    /**
     * Amount in minor unit (e.g. pence in GBP, cents in EUR).
     */
    protected $amount;

    /**
     * Date the payout is due to arrive in the creditor's bank account.
     * One of:
     *
     * <ul>
     * <li><code>yyyy-mm-dd</code>: the payout has been paid and is due to
     * arrive in the creditor's bank account on this day</li>
     * <li><code>null</code>: the payout hasn't been paid yet</li>
     * </ul>
     */
    protected $arrival_date;

    /**
     * Fixed <a
     * href="https://developer.gocardless.com/api-reference/#api-usage-dates-and-times">timestamp</a>,
     * recording when this resource was created.
     */
    protected $created_at;

    /**
     * <a href="https://en.wikipedia.org/wiki/ISO_4217#Active_codes">ISO
     * 4217</a> currency code. Currently "AUD", "CAD", "DKK", "EUR", "GBP",
     * "NZD", "SEK" and "USD" are supported.
     */
    protected $currency;

    /**
     * Fees that have already been deducted from the payout amount in minor unit
     * (e.g. pence in GBP, cents in EUR), inclusive of tax if applicable.
     * <br></br>
     * For each <code>late_failure_settled</code> or
     * <code>chargeback_settled</code> action, we refund the transaction fees in
     * a payout. This means that a payout can have a negative
     * <code>deducted_fees</code> value.
     * <br></br>
     * This field is calculated as <code>(GoCardless fees + app fees + surcharge
     * fees) - (refunded fees)</code>
     * <br></br>
     * If the merchant is invoiced for fees separately from the payout, then
     * <code>deducted_fees</code> will be 0.
     */
    protected $deducted_fees;

    /**
     *
     */
    protected $fx;

    /**
     * Unique identifier, beginning with "PO".
     */
    protected $id;

    /**
     *
     */
    protected $links;

    /**
     * Key-value store of custom data. Up to 3 keys are permitted, with key
     * names up to 50 characters and values up to 500 characters. <em>Note:</em>
     * This should not be used for storing PII data.
     */
    protected $metadata;

    /**
     * Whether a payout contains merchant revenue or partner fees.
     */
    protected $payout_type;

    /**
     * Reference which appears on the creditor's bank statement.
     */
    protected $reference;

    /**
     * One of:
     *
     * <ul>
     * <li><code>pending</code>: the payout has been created, but not yet sent
     * to your bank or it is in the process of being exchanged through our FX
     * provider.</li>
     * <li><code>paid</code>: the payout has been sent to the your bank. FX
     * payouts will become <code>paid</code> after we emit the
     * <code>fx_rate_confirmed</code> webhook.</li>
     * <li><code>bounced</code>: the payout bounced when sent, the payout can be
     * retried.</li>
     * </ul>
     */
    protected $status;

    /**
     * <a href="https://en.wikipedia.org/wiki/ISO_4217#Active_codes">ISO
     * 4217</a> code for the currency in which tax is paid out to the tax
     * authorities of your tax jurisdiction. Currently “EUR”, “GBP”, for French
     * or British merchants, this will be <code>null</code> if tax is not
     * applicable <em>beta</em>
     */
    protected $tax_currency;
}
