<?php
/**
 * WARNING: Do not edit by hand, this file was generated by Crank:
 *
 * https://github.com/gocardless/crank
 */

namespace GoCardlessPro\Resources;

/**
 * A thin wrapper around a redirect_flow, providing access to it's
 * attributes
 *
 * @property-read $created_at
 * @property-read $description
 * @property-read $id
 * @property-read $links
 * @property-read $redirect_url
 * @property-read $scheme
 * @property-read $session_token
 * @property-read $success_redirect_url
 */
class RedirectFlow extends BaseResource
{
    protected $model_name = "RedirectFlow";

    /**
     * Fixed [timestamp](#overview-time-zones-dates), recording when this
     * resource was created.
     */
    protected $created_at;

    /**
     * A description of the item the customer is paying for. This will be shown
     * on the hosted payment pages.
     */
    protected $description;

    /**
     * Unique identifier, beginning with "RE".
     */
    protected $id;

    /**
     * 
     */
    protected $links;

    /**
     * The URL of the hosted payment pages for this redirect flow. This is the
     * URL you should redirect your customer to.
     */
    protected $redirect_url;

    /**
     * The Direct Debit scheme of the mandate. If specified, the payment pages
     * will only allow the set-up of a mandate for the specified scheme.
     */
    protected $scheme;

    /**
     * The customer's session ID must be provided when the redirect flow is set
     * up and again when it is completed. This allows integrators to ensure that
     * the user who was originally sent to the GoCardless payment pages is the
     * one who has completed them.
     */
    protected $session_token;

    /**
     * The URL to redirect to upon successful mandate setup. You must use a URL
     * beginning `https` in the live environment.
     */
    protected $success_redirect_url;

}
