<?php

/**
 * WARNING: Do not edit by hand, this file was generated by Crank:
 *
 * https://github.com/gocardless/crank
 */

namespace GoCardlessPro\Resources;

/**
 * A thin wrapper around a refund, providing access to its
 * attributes
 *
 * @property-read mixed $amount
 * @property-read mixed $created_at
 * @property-read mixed $currency
 * @property-read mixed $fx
 * @property-read mixed $id
 * @property-read mixed $links
 * @property-read mixed $metadata
 * @property-read mixed $reference
 * @property-read mixed $status
 */
class Refund extends BaseResource
{
    protected $model_name = "Refund";

    /**
     * Amount in minor unit (e.g. pence in GBP, cents in EUR).
     */
    protected $amount;

    /**
     * Fixed timestamp
     * (https://developer.gocardless.com/api-reference/#api-usage-dates-and-times),
     * recording when this resource was created.
     */
    protected $created_at;

    /**
     * ISO 4217 (https://en.wikipedia.org/wiki/ISO_4217#Active_codes) currency
     * code. This is set to the currency of the refund's payment
     * (https://developer.gocardless.com/api-reference/#core-endpoints-payments).
     */
    protected $currency;

    /**
     *
     */
    protected $fx;

    /**
     * Unique identifier, beginning with "RF".
     */
    protected $id;

    /**
     *
     */
    protected $links;

    /**
     * Key-value store of custom data. Up to 3 keys are permitted, with key
     * names up to 50 characters and values up to 500 characters.
     */
    protected $metadata;

    /**
     * An optional reference that will appear on your customer's bank statement.
     * The character limit for this reference is dependent on the scheme.
     *  ACH <ul>
     * <li>10 characters</li>
     * </ul>
     *  Autogiro <ul>
     * <li>11 characters</li>
     * </ul>
     *  Bacs <ul>
     * <li>10 characters</li>
     * </ul>
     *  BECS <ul>
     * <li>30 characters</li>
     * </ul>
     *  BECS NZ <ul>
     * <li>12 characters</li>
     * </ul>
     *  Betalingsservice <ul>
     * <li>30 characters</li>
     * </ul>
     *  Faster Payments <ul>
     * <li>18 characters</li>
     * </ul>
     *  PAD <ul>
     * <li>scheme doesn't offer references</li>
     * </ul>
     *  PayTo <ul>
     * <li>18 characters</li>
     * </ul>
     *  SEPA <ul>
     * <li>140 characters</li>
     * </ul>
     *  Note that this reference must be unique (for each merchant) for the BECS
     * scheme as it is a scheme requirement. Restricted: You can only specify a
     * payment reference for Bacs payments (that is, when collecting from the
     * UK) if you're on the GoCardless Plus, Pro or Enterprise packages
     * (https://gocardless.com/pricing).
     *  Restricted: You can not specify a payment reference for Faster Payments.
     */
    protected $reference;

    /**
     * One of:
     *
     * - `created`: the refund has been created
     * - `pending_submission`: the refund has been created, but not yet
     * submitted to the banks
     * - `submitted`: the refund has been submitted to the banks
     * - `paid`:  the refund has been included in a payout
     * (https://developer.gocardless.com/api-reference/#core-endpoints-payouts)
     * - `cancelled`: the refund has been cancelled
     * - `bounced`: the refund has failed to be paid
     * - `funds_returned`: the refund has had its funds returned
     */
    protected $status;
}
