<?php
/**
 * WARNING: Do not edit by hand, this file was generated by Crank:
 *
 * https://github.com/gocardless/crank
 */

namespace GoCardlessPro\Resources;

/**
 * A thin wrapper around a refund, providing access to its
 * attributes
 *
 * @property-read $amount
 * @property-read $created_at
 * @property-read $currency
 * @property-read $id
 * @property-read $links
 * @property-read $metadata
 * @property-read $reference
 */
class Refund extends BaseResource
{
    protected $model_name = "Refund";

    /**
     * Amount in pence/cents/öre.
     */
    protected $amount;

    /**
     * Fixed [timestamp](#api-usage-time-zones--dates), recording when this
     * resource was created.
     */
    protected $created_at;

    /**
     * [ISO 4217](http://en.wikipedia.org/wiki/ISO_4217#Active_codes) currency
     * code. This is set to the currency of the refund's
     * [payment](#core-endpoints-payments).
     */
    protected $currency;

    /**
     * Unique identifier, beginning with "RF".
     */
    protected $id;

    /**
     * 
     */
    protected $links;

    /**
     * Key-value store of custom data. Up to 3 keys are permitted, with key
     * names up to 50 characters and values up to 500 characters.
     */
    protected $metadata;

    /**
     * An optional refund reference, displayed on your customer's bank
     * statement. This can be up to 18 characters long for Bacs or BECS
     * payments, 140 characters for SEPA payments, or 25 characters for Autogiro
     * payments.
     */
    protected $reference;

}
