<?php
/**
 * WARNING: Do not edit by hand, this file was generated by Crank:
 *
 * https://github.com/gocardless/crank
 */

namespace GoCardlessPro\Resources;

/**
 * A thin wrapper around a scenario_simulator, providing access to its
 * attributes
 *
 * @property-read $description
 * @property-read $id
 * @property-read $name
 * @property-read $resource_type
 */
class ScenarioSimulator extends BaseResource
{
    protected $model_name = "ScenarioSimulator";

    /**
     * A short description of what the simulator does and anything you should
     * know about using it (e.g. what state the resource should be in).
     */
    protected $description;

    /**
     * The unique identifier of the simulator, used to initiate simulations. One
     * of:
     * <ul>
     * <li>`creditor_verification_status_action_required`</li>
     * <li>`creditor_verification_status_in_review`</li>
     * <li>`creditor_verification_status_successful`</li>
     * <li>`payment_paid_out`</li>
     * <li>`payment_failed`</li>
     * <li>`payment_charged_back`</li>
     * <li>`payment_late_failure`</li>
     * <li>`payment_late_failure_settled`</li>
     * <li>`payment_submitted`</li>
     * <li>`mandate_activated`</li>
     * <li>`mandate_failed`</li>
     * <li>`mandate_expired`</li>
     * <li>`mandate_transferred`</li>
     * <li>`refund_paid`</li>
     * <li>`payout_bounced`</li>
     * </ul>
     */
    protected $id;

    /**
     * The name of the simulator, suitable for displaying to the user,
     * translated into their language
     */
    protected $name;

    /**
     * The type of resource which the simulator operates on
     */
    protected $resource_type;

}
