<?php
/**
 * WARNING: Do not edit by hand, this file was generated by Crank:
 *
 *   https://github.com/gocardless/crank
 */

namespace GoCardless\Core;

/**
  * Wrapper for a list of models in a response
  * Decodes from a Response
  * @subpackage Core
  */
class ListResponse extends \ArrayObject
{
    /** @var array internal list of models */
    private $models = array();
    /** @var Response response object */
    private $response;
    /** @var string response object type (fully-qualified classname within \GoCardless\Resources) */
    private $modelClass;

    /**
      * Creates a new list response of the same model class and decodes
      * the array from the raw response.
      *
      * @param string $modelClass
      * @param Response $response 
      */
    public function __construct($modelClass, $response)
    {
        $this->modelClass = $modelClass;
        $this->response = $response;
        foreach ($response->response() as $item) {
            $this->models[] = new $modelClass($item);
        }
        parent::__construct($this->models);
    }

    /**
      * HTTP response information
      *
      * @return Response
      */
    public function response()
    {
        return $this->response;
    }

    /**
      * Gets an array of resources in the list
      *
      * @return array
      */
    public function items()
    {
        return $this->models;
    }

    /**
      * Accessor to the response's meta object in a NestedObject wrapper
      *
      * @return \GoCardless\Resources\Wrapper\NestedObject
      */
    public function meta()
    {
        return $this->response->meta();
    }
}
