<?php
//
// WARNING: Do not edit by hand, this file was generated by Crank:
// https://github.com/gocardless/crank
//

namespace GoCardlessPro\Integration;

class BalancesIntegrationTest extends IntegrationTestBase
{
    public function testResourceModelExists()
    {
        $obj = new \GoCardlessPro\Resources\Balance(array());
        $this->assertNotNull($obj);
    }
    
    public function testBalancesList()
    {
        $fixture = $this->loadJsonFixture('balances')->list;
        $this->stub_request($fixture);

        $service = $this->client->balances();
        $response = call_user_func_array(array($service, 'list'), (array)$fixture->url_params);

        $body = $fixture->body->balances;
    
        $records = $response->records;
        $this->assertInstanceOf('\GoCardlessPro\Core\ListResponse', $response);
        $this->assertInstanceOf('\GoCardlessPro\Resources\Balance', $records[0]);
        if (!is_null($fixture->body) && property_exists($fixture->body, 'meta') && !is_null($fixture->body->meta)) {
            $this->assertEquals($fixture->body->meta->cursors->before, $response->before);
            $this->assertEquals($fixture->body->meta->cursors->after, $response->after);
        }
    

    
        foreach (range(0, count($body) - 1) as $num) {
            $record = $records[$num];
            
                if (isset($body[$num]->amount)) {
                    $this->assertEquals($body[$num]->amount, $record->amount);
                }
            
                if (isset($body[$num]->balance_type)) {
                    $this->assertEquals($body[$num]->balance_type, $record->balance_type);
                }
            
                if (isset($body[$num]->currency)) {
                    $this->assertEquals($body[$num]->currency, $record->currency);
                }
            
                if (isset($body[$num]->last_updated_at)) {
                    $this->assertEquals($body[$num]->last_updated_at, $record->last_updated_at);
                }
            
                if (isset($body[$num]->links)) {
                    $this->assertEquals($body[$num]->links, $record->links);
                }
            
        }

        $expectedPathRegex = $this->extract_resource_fixture_path_regex($fixture);
        $dispatchedRequest = $this->history[0]['request'];
        $this->assertMatchesRegularExpression($expectedPathRegex, $dispatchedRequest->getUri()->getPath());
    }

    
}
