<?php

//
// WARNING: Do not edit by hand, this file was generated by Crank:
// https://github.com/gocardless/crank
//

namespace GoCardlessPro\Integration;

class BankAccountHolderVerificationsIntegrationTest extends IntegrationTestBase
{
    public function testResourceModelExists()
    {
        $obj = new \GoCardlessPro\Resources\BankAccountHolderVerification(array());
        $this->assertNotNull($obj);
    }

    public function testBankAccountHolderVerificationsCreate()
    {
        $fixture = $this->loadJsonFixture('bank_account_holder_verifications')->create;
        $this->stub_request($fixture);

        $service = $this->client->bankAccountHolderVerifications();
        $response = call_user_func_array(array($service, 'create'), (array)$fixture->url_params);

        $body = $fixture->body->bank_account_holder_verifications;

        $this->assertInstanceOf('\GoCardlessPro\Resources\BankAccountHolderVerification', $response);

        $this->assertEquals($body->actual_account_name, $response->actual_account_name);
        $this->assertEquals($body->id, $response->id);
        $this->assertEquals($body->result, $response->result);
        $this->assertEquals($body->status, $response->status);
        $this->assertEquals($body->type, $response->type);


        $expectedPathRegex = $this->extract_resource_fixture_path_regex($fixture);
        $dispatchedRequest = $this->history[0]['request'];
        $this->assertMatchesRegularExpression($expectedPathRegex, $dispatchedRequest->getUri()->getPath());
    }

    public function testBankAccountHolderVerificationsCreateWithIdempotencyConflict()
    {
        $fixture = $this->loadJsonFixture('bank_account_holder_verifications')->create;

        $idempotencyConflictResponseFixture = $this->loadFixture('idempotent_creation_conflict_invalid_state_error');

        // The POST request responds with a 409 to our original POST, due to an idempotency conflict
        $this->mock->append(new \GuzzleHttp\Psr7\Response(409, [], $idempotencyConflictResponseFixture));

        // The client makes a second request to fetch the resource that was already
        // created using our idempotency key. It responds with the created resource,
        // which looks just like the response for a successful POST request.
        $this->mock->append(new \GuzzleHttp\Psr7\Response(200, [], json_encode($fixture->body)));

        $service = $this->client->bankAccountHolderVerifications();
        $response = call_user_func_array(array($service, 'create'), (array)$fixture->url_params);
        $body = $fixture->body->bank_account_holder_verifications;

        $this->assertInstanceOf('\GoCardlessPro\Resources\BankAccountHolderVerification', $response);

        $this->assertEquals($body->actual_account_name, $response->actual_account_name);
        $this->assertEquals($body->id, $response->id);
        $this->assertEquals($body->result, $response->result);
        $this->assertEquals($body->status, $response->status);
        $this->assertEquals($body->type, $response->type);


        $expectedPathRegex = $this->extract_resource_fixture_path_regex($fixture);
        $conflictRequest = $this->history[0]['request'];
        $this->assertMatchesRegularExpression($expectedPathRegex, $conflictRequest->getUri()->getPath());
        $getRequest = $this->history[1]['request'];
        $this->assertEquals($getRequest->getUri()->getPath(), '/bank_account_holder_verifications/ID123');
    }

    public function testBankAccountHolderVerificationsGet()
    {
        $fixture = $this->loadJsonFixture('bank_account_holder_verifications')->get;
        $this->stub_request($fixture);

        $service = $this->client->bankAccountHolderVerifications();
        $response = call_user_func_array(array($service, 'get'), (array)$fixture->url_params);

        $body = $fixture->body->bank_account_holder_verifications;

        $this->assertInstanceOf('\GoCardlessPro\Resources\BankAccountHolderVerification', $response);

        $this->assertEquals($body->actual_account_name, $response->actual_account_name);
        $this->assertEquals($body->id, $response->id);
        $this->assertEquals($body->result, $response->result);
        $this->assertEquals($body->status, $response->status);
        $this->assertEquals($body->type, $response->type);


        $expectedPathRegex = $this->extract_resource_fixture_path_regex($fixture);
        $dispatchedRequest = $this->history[0]['request'];
        $this->assertMatchesRegularExpression($expectedPathRegex, $dispatchedRequest->getUri()->getPath());
    }
}
