<?php

//
// WARNING: Do not edit by hand, this file was generated by Crank:
// https://github.com/gocardless/crank
//

namespace GoCardlessPro\Integration;

class FundsAvailabilitiesIntegrationTest extends IntegrationTestBase
{
    public function testResourceModelExists()
    {
        $obj = new \GoCardlessPro\Resources\FundsAvailability(array());
        $this->assertNotNull($obj);
    }

    public function testFundsAvailabilitiesCheck()
    {
        $fixture = $this->loadJsonFixture('funds_availabilities')->check;
        $this->stub_request($fixture);

        $service = $this->client->fundsAvailabilities();
        $response = call_user_func_array(array($service, 'check'), (array)$fixture->url_params);

        $body = $fixture->body->funds_availability;

        $this->assertInstanceOf('\GoCardlessPro\Resources\FundsAvailability', $response);


        if (property_exists($body, 'available')) {
            $this->assertEquals($body->available, $response->available);
        }


        $expectedPathRegex = $this->extract_resource_fixture_path_regex($fixture);
        $dispatchedRequest = $this->history[0]['request'];
        $this->assertMatchesRegularExpression($expectedPathRegex, $dispatchedRequest->getUri()->getPath());
    }
}
