<?php

//
// WARNING: Do not edit by hand, this file was generated by Crank:
// https://github.com/gocardless/crank
//

namespace GoCardlessPro\Integration;

class OutboundPaymentImportEntriesIntegrationTest extends IntegrationTestBase
{
    public function testResourceModelExists()
    {
        $obj = new \GoCardlessPro\Resources\OutboundPaymentImportEntry(array());
        $this->assertNotNull($obj);
    }

    public function testOutboundPaymentImportEntriesList()
    {
        $fixture = $this->loadJsonFixture('outbound_payment_import_entries')->list;
        $this->stubRequest($fixture);

        $service = $this->client->outboundPaymentImportEntries();
        $response = call_user_func_array(array($service, 'list'), (array)$fixture->url_params);

        $body = $fixture->body->outbound_payment_import_entries;

        $records = $response->records;
        $this->assertInstanceOf('\GoCardlessPro\Core\ListResponse', $response);
        $this->assertInstanceOf('\GoCardlessPro\Resources\OutboundPaymentImportEntry', $records[0]);
        if (!is_null($fixture->body) && property_exists($fixture->body, 'meta') && !is_null($fixture->body->meta)) {
            $this->assertEquals($fixture->body->meta->cursors->before, $response->before);
            $this->assertEquals($fixture->body->meta->cursors->after, $response->after);
        }



        foreach (range(0, count($body) - 1) as $num) {
            $record = $records[$num];

            if (isset($body[$num]->amount)) {
                $this->assertEquals($body[$num]->amount, $record->amount);
            }

            if (isset($body[$num]->created_at)) {
                $this->assertEquals($body[$num]->created_at, $record->created_at);
            }

            if (isset($body[$num]->id)) {
                $this->assertEquals($body[$num]->id, $record->id);
            }

            if (isset($body[$num]->links)) {
                $this->assertEquals($body[$num]->links, $record->links);
            }

            if (isset($body[$num]->metadata)) {
                $this->assertEquals($body[$num]->metadata, $record->metadata);
            }

            if (isset($body[$num]->processed_at)) {
                $this->assertEquals($body[$num]->processed_at, $record->processed_at);
            }

            if (isset($body[$num]->reference)) {
                $this->assertEquals($body[$num]->reference, $record->reference);
            }

            if (isset($body[$num]->scheme)) {
                $this->assertEquals($body[$num]->scheme, $record->scheme);
            }

            if (isset($body[$num]->validation_errors)) {
                $this->assertEquals($body[$num]->validation_errors, $record->validation_errors);
            }

            if (isset($body[$num]->verification_result)) {
                $this->assertEquals($body[$num]->verification_result, $record->verification_result);
            }
        }

        $expectedPathRegex = $this->extractResourceFixturePathRegex($fixture);
        $dispatchedRequest = $this->history[0]['request'];
        $this->assertMatchesRegularExpression($expectedPathRegex, $dispatchedRequest->getUri()->getPath());
    }
}
