<?php

//
// WARNING: Do not edit by hand, this file was generated by Crank:
// https://github.com/gocardless/crank
//

namespace GoCardlessPro\Integration;

class OutboundPaymentImportsIntegrationTest extends IntegrationTestBase
{
    public function testResourceModelExists()
    {
        $obj = new \GoCardlessPro\Resources\OutboundPaymentImport(array());
        $this->assertInstanceOf('\GoCardlessPro\Resources\OutboundPaymentImport', $obj);
    }

    public function testOutboundPaymentImportsCreate()
    {
        $fixture = $this->loadJsonFixture('outbound_payment_imports')->create;
        $this->stubRequest($fixture);

        $service = $this->client->outboundPaymentImports();
        $response = call_user_func_array(array($service, 'create'), (array)$fixture->url_params);

        $body = $fixture->body->outbound_payment_imports;

        $this->assertInstanceOf('\GoCardlessPro\Resources\OutboundPaymentImport', $response);


        if (property_exists($body, 'amount_sum')) {
            $this->assertEquals($body->amount_sum, $response->amount_sum);
        }

        if (property_exists($body, 'authorisation_url')) {
            $this->assertEquals($body->authorisation_url, $response->authorisation_url);
        }

        if (property_exists($body, 'created_at')) {
            $this->assertEquals($body->created_at, $response->created_at);
        }

        if (property_exists($body, 'currency')) {
            $this->assertEquals($body->currency, $response->currency);
        }

        if (property_exists($body, 'entry_counts')) {
            $this->assertEquals($body->entry_counts, $response->entry_counts);
        }

        if (property_exists($body, 'id')) {
            $this->assertEquals($body->id, $response->id);
        }

        if (property_exists($body, 'links')) {
            $this->assertEquals($body->links, $response->links);
        }

        if (property_exists($body, 'status')) {
            $this->assertEquals($body->status, $response->status);
        }


        $expectedPathRegex = $this->extractResourceFixturePathRegex($fixture);
        $dispatchedRequest = $this->history[0]['request'];
        $this->assertMatchesRegularExpression($expectedPathRegex, $dispatchedRequest->getUri()->getPath());
    }

    public function testOutboundPaymentImportsCreateWithIdempotencyConflict()
    {
        $fixture = $this->loadJsonFixture('outbound_payment_imports')->create;

        $idempotencyConflictResponseFixture = $this->loadFixture('idempotent_creation_conflict_invalid_state_error');

        // The POST request responds with a 409 to our original POST, due to an idempotency conflict
        $this->mock->append(new \GuzzleHttp\Psr7\Response(409, [], $idempotencyConflictResponseFixture));

        // The client makes a second request to fetch the resource that was already
        // created using our idempotency key. It responds with the created resource,
        // which looks just like the response for a successful POST request.
        $this->mock->append(new \GuzzleHttp\Psr7\Response(200, [], json_encode($fixture->body)));

        $service = $this->client->outboundPaymentImports();
        $response = call_user_func_array(array($service, 'create'), (array)$fixture->url_params);
        $body = $fixture->body->outbound_payment_imports;

        $this->assertInstanceOf('\GoCardlessPro\Resources\OutboundPaymentImport', $response);

        if (property_exists($body, 'amount_sum')) {
            $this->assertEquals($body->amount_sum, $response->amount_sum);
        }
        if (property_exists($body, 'authorisation_url')) {
            $this->assertEquals($body->authorisation_url, $response->authorisation_url);
        }
        if (property_exists($body, 'created_at')) {
            $this->assertEquals($body->created_at, $response->created_at);
        }
        if (property_exists($body, 'currency')) {
            $this->assertEquals($body->currency, $response->currency);
        }
        if (property_exists($body, 'entry_counts')) {
            $this->assertEquals($body->entry_counts, $response->entry_counts);
        }
        if (property_exists($body, 'id')) {
            $this->assertEquals($body->id, $response->id);
        }
        if (property_exists($body, 'links')) {
            $this->assertEquals($body->links, $response->links);
        }
        if (property_exists($body, 'status')) {
            $this->assertEquals($body->status, $response->status);
        }


        $expectedPathRegex = $this->extractResourceFixturePathRegex($fixture);
        $conflictRequest = $this->history[0]['request'];
        $this->assertMatchesRegularExpression($expectedPathRegex, $conflictRequest->getUri()->getPath());
        $getRequest = $this->history[1]['request'];
        $this->assertEquals($getRequest->getUri()->getPath(), '/outbound_payment_imports/ID123');
    }

    public function testOutboundPaymentImportsGet()
    {
        $fixture = $this->loadJsonFixture('outbound_payment_imports')->get;
        $this->stubRequest($fixture);

        $service = $this->client->outboundPaymentImports();
        $response = call_user_func_array(array($service, 'get'), (array)$fixture->url_params);

        $body = $fixture->body->outbound_payment_imports;

        $this->assertInstanceOf('\GoCardlessPro\Resources\OutboundPaymentImport', $response);


        if (property_exists($body, 'amount_sum')) {
            $this->assertEquals($body->amount_sum, $response->amount_sum);
        }

        if (property_exists($body, 'authorisation_url')) {
            $this->assertEquals($body->authorisation_url, $response->authorisation_url);
        }

        if (property_exists($body, 'created_at')) {
            $this->assertEquals($body->created_at, $response->created_at);
        }

        if (property_exists($body, 'currency')) {
            $this->assertEquals($body->currency, $response->currency);
        }

        if (property_exists($body, 'entry_counts')) {
            $this->assertEquals($body->entry_counts, $response->entry_counts);
        }

        if (property_exists($body, 'id')) {
            $this->assertEquals($body->id, $response->id);
        }

        if (property_exists($body, 'links')) {
            $this->assertEquals($body->links, $response->links);
        }

        if (property_exists($body, 'status')) {
            $this->assertEquals($body->status, $response->status);
        }


        $expectedPathRegex = $this->extractResourceFixturePathRegex($fixture);
        $dispatchedRequest = $this->history[0]['request'];
        $this->assertMatchesRegularExpression($expectedPathRegex, $dispatchedRequest->getUri()->getPath());
    }


    public function testOutboundPaymentImportsList()
    {
        $fixture = $this->loadJsonFixture('outbound_payment_imports')->list;
        $this->stubRequest($fixture);

        $service = $this->client->outboundPaymentImports();
        $response = call_user_func_array(array($service, 'list'), (array)$fixture->url_params);

        $body = $fixture->body->outbound_payment_imports;

        $records = $response->records;
        $this->assertInstanceOf('\GoCardlessPro\Core\ListResponse', $response);
        $this->assertInstanceOf('\GoCardlessPro\Resources\OutboundPaymentImport', $records[0]);
        if (!is_null($fixture->body) && property_exists($fixture->body, 'meta') && !is_null($fixture->body->meta)) {
            $this->assertEquals($fixture->body->meta->cursors->before, $response->before);
            $this->assertEquals($fixture->body->meta->cursors->after, $response->after);
        }



        foreach (range(0, count($body) - 1) as $num) {
            $record = $records[$num];

            if (isset($body[$num]->amount_sum)) {
                $this->assertEquals($body[$num]->amount_sum, $record->amount_sum);
            }

            if (isset($body[$num]->authorisation_url)) {
                $this->assertEquals($body[$num]->authorisation_url, $record->authorisation_url);
            }

            if (isset($body[$num]->created_at)) {
                $this->assertEquals($body[$num]->created_at, $record->created_at);
            }

            if (isset($body[$num]->currency)) {
                $this->assertEquals($body[$num]->currency, $record->currency);
            }

            if (isset($body[$num]->entry_counts)) {
                $this->assertEquals($body[$num]->entry_counts, $record->entry_counts);
            }

            if (isset($body[$num]->id)) {
                $this->assertEquals($body[$num]->id, $record->id);
            }

            if (isset($body[$num]->links)) {
                $this->assertEquals($body[$num]->links, $record->links);
            }

            if (isset($body[$num]->status)) {
                $this->assertEquals($body[$num]->status, $record->status);
            }
        }

        $expectedPathRegex = $this->extractResourceFixturePathRegex($fixture);
        $dispatchedRequest = $this->history[0]['request'];
        $this->assertMatchesRegularExpression($expectedPathRegex, $dispatchedRequest->getUri()->getPath());
    }
}
