<?php
/**
  * WARNING: Do not edit by hand, this file was generated by Crank:
  *
  * https://github.com/gocardless/crank
  */

namespace GoCardlessPro\Services;

/**
  *  Mandate PDFs
  *

  *
  *  Construct a mandate PDF for a given set of bank details or an
  *  already-existing mandate.
  */
class MandatePdfsService extends Base
{
  
  /**
    *  Generate a mandate PDF
    *
    *  Generates a temporary URL for viewing a PDF mandate.
    *  
    *  Bank
    *  account details may be supplied using an IBAN (international bank account
    *  number), or [local details](#ui-local-bank-details), or alternatively you
    *  can provide the ID of an existing [mandate](#core-endpoints-mandates) to
    *  create a PDF of.
    *  
    *  To generate a mandate in a foreign
    *  language, set your `Accept-Language` header to the relevant [ISO
    *  639-1](http://en.wikipedia.org/wiki/List_of_ISO_639-1_codes#Partial_ISO_639_table)
    *  language code. Currently Dutch, English, French, German, Italian,
    *  Portuguese and Spanish are supported.
    *
    *  Example URL: /mandate_pdfs
    *
    *
    * @param array $params POST/URL parameters for the argument. Automatically wrapped.
    * @param array $headers String to string associative array of custom headers to add to the requestion.
    *
    * @return MandatePdf
    * @throws \GoCardlessPro\Core\Error\GoCardlessError GoCardless API or server error, subclasses thereof.
    * @throws \GoCardlessPro\Core\Error\HttpError PHP Curl transport layer-level errors.
    **/
    public function create($params = array(), $headers = array())
    {
        return $this->make_request('create', 'post', '/mandate_pdfs', $params, $headers);
    }




   /**
    * Get the resource loading class.
    * Used internally to send http requests.
    *
    * @return string
    */
    protected function resourceClass()
    {
        return '\GoCardlessPro\Resources\MandatePdf';
    }

  /**
    *  Get the key the response object is enclosed in in JSON.
    *  Used internally to wrap and unwrap http requests.
    *
    *  @return string
    */
    protected function envelopeKey()
    {
        return 'mandate_pdfs';
    }
}
