<?php
/**
  * WARNING: Do not edit by hand, this file was generated by Crank:
  *
  * https://github.com/gocardless/crank
  */

namespace GoCardlessPro\Services;

/**
  *  Modulus Checks
  *

  *
  *  Check whether an account number and bank / branch code combination are
  *  compatible.
  */
class ModulusChecksService extends Base
{
  
  /**
    *  Perform a modulus check
    *
    *  Performs a modulus check.
    *  
    *  Bank account details may either
    *  be supplied using the IBAN (international bank account number), or [local
    *  details](#ui-compliance-local-bank-details). For more information on the
    *  different fields required in each country, please see the [local bank
    *  details](#ui-compliance-local-bank-details) section.
    *
    *  Example URL: /modulus_checks
    *
    *
    * @param array $params POST/URL parameters for the argument. Automatically wrapped.
    * @param array $headers String to string associative array of custom headers to add to the requestion.
    *
    * @return ModulusCheck
    * @throws \GoCardlessPro\Core\Error\GoCardlessError GoCardless API or server error, subclasses thereof.
    * @throws \GoCardlessPro\Core\Error\HttpError PHP Curl transport layer-level errors.
    **/
    public function create($params = array(), $headers = array())
    {
        return $this->make_request('create', 'post', '/modulus_checks', $params, $headers);
    }




   /**
    * Get the resource loading class.
    * Used internally to send http requests.
    *
    * @return string
    */
    protected function resourceClass()
    {
        return '\GoCardlessPro\Resources\ModulusCheck';
    }

  /**
    *  Get the key the response object is enclosed in in JSON.
    *  Used internally to wrap and unwrap http requests.
    *
    *  @return string
    */
    protected function envelopeKey()
    {
        return 'modulus_checks';
    }
}
