<?php

/**
 * WARNING: Do not edit by hand, this file was generated by Crank:
 *
 *   https://github.com/gocardless/crank
 */

namespace GoCardlessPro\Core;

use GoCardlessPro\Core\Exception\ApiException;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Psr7\Response;

/**
 * HTTP Client class wrapped by the Client class and
 * used internally to route http requests.
 */
class ApiClient
{
    private $http_client;
    public $error_on_idempotency_conflict;

    /**
     * @param \GuzzleHttp\ClientInterface $http_client  An HTTP client to make requests
     * @param array $config configuration for the ApiClient
     */
    public function __construct(ClientInterface $http_client, array $config)
    {
        $this->http_client = $http_client;
        $this->error_on_idempotency_conflict = $config['error_on_idempotency_conflict'];
    }

    /**
     * Make a GET request to the API
     *
     * @param string $path   The relative path for the API request. e.g. /records
     * @param array  $params Any query params to send with the request
     *
     * @return \GuzzleHttp\Psr7\Response The raw response
     */
    public function get(string $path, array $params = []): Response
    {
        $this->validatePath($path);

        if (array_key_exists("query", $params)) {
            $params["query"] = $this->castBooleanValuesToStrings($params["query"]);
        }

        $response = $this->http_client->request('GET', $path, $params);
        $this->handleErrors($response);
        return $response;
    }

    /**
     * Make a PUT request to the API
     *
     * @param string $path   The relative path for the API request. e.g. /records
     * @param array  $params Body of the request, will be serialized to JSON
     *
     * @return \GuzzleHttp\Psr7\Response The raw response
     */
    public function put(string $path, array $params): Response
    {
        $this->validatePath($path);

        $response = $this->http_client->request('PUT', $path, $params);
        $this->handleErrors($response);
        return $response;
    }

    /**
     * Make a POST request to the API
     *
     * @param string $path   The relative path for the API request. e.g. /records
     * @param array  $params Body of the request, will be serialized to JSON
     *
     * @return \GuzzleHttp\Psr7\Response The raw response
     */
    public function post(string $path, array $params): Response
    {
        $this->validatePath($path);

        $idempotencyKey = uniqid("", true);
        $paramsWithHeaders = array("headers" => array("Idempotency-Key" => $idempotencyKey));
        $params = array_replace_recursive($paramsWithHeaders, $params);

        $response = $this->http_client->request('POST', $path, $params);

        $this->handleErrors($response);
        return $response;
    }

    /**
     * Make a DELETE request to the API
     *
     * @param string $path   The relative path for the API request. e.g. /records
     * @param array  $params Body of the request, will be serialized to JSON
     *
     * @return \GuzzleHttp\Psr7\Response The raw response
     */
    public function delete(string $path, array $params): Response
    {
        $this->validatePath($path);

        $idempotencyKey = uniqid("", true);
        $paramsWithHeaders = array("headers" => array("Idempotency-Key" => $idempotencyKey));
        $params = array_replace_recursive($paramsWithHeaders, $params);

        $response = $this->http_client->request('DELETE', $path, $params);

        $this->handleErrors($response);
        return $response;
    }

    /**
     * Check that a request path cannot move the request off the configured base URL.
     *
     * Guzzle resolves $path against base_uri like a browser resolves a link, so an
     * absolute or scheme-relative path replaces the configured origin while the
     * Authorization header stays attached. Checked with parse_url, the same parser
     * Guzzle's own URI handling uses. Dot segments are left alone, since they resolve
     * against base_uri and can't leave its origin.
     *
     * @param string $path The relative path for the API request
     *
     * @throws \InvalidArgumentException if the path is not a relative reference
     */
    private function validatePath(string $path)
    {
        $parsed = parse_url($path);

        if ($parsed === false) {
            throw new \InvalidArgumentException(
                "Invalid request path '" . $path . "': not a valid URL path."
            );
        }

        if (isset($parsed["scheme"]) || isset($parsed["host"])) {
            throw new \InvalidArgumentException(
                "Invalid request path '" . $path . "': a path may not specify a scheme or a " .
                "host, only a location relative to the configured base URL."
            );
        }
    }

    /**
     * Handle any errors in the API response
     *
     * If the response status is 204 - No Content, then we can skip response body
     * JSON checks.
     *
     * If the response doesn't contain JSON, we will fail to decode and throw a
     * MalFormedResponseException.
     *
     * If the response is JSON, but the status code is >= 400, then we return
     * the appropriate error depending on the code
     *
     * @param \GuzzleHttp\Psr7\Response $response The raw API response
     */
    private function handleErrors(Response $response)
    {
        if ($response->getStatusCode() === 204) {
            return null;
        }

        $status_code = $response->getStatusCode();
        $json = json_decode($response->getBody());

        if ($json === null) {
            $msg = "Malformed response received from server";
            throw new Exception\MalformedResponseException($msg, $response, $status_code);
        }

        if ($status_code < 400) {
            return null;
        }

        // Normalize string errors into standard error object format
        if (is_string($json->error)) {
            $json->error = (object)[
                'code' => $status_code,
                'message' => $json->error
            ];
            // Create a new response with normalized error structure
            $response = new Response(
                $status_code,
                $response->getHeaders(),
                json_encode($json)
            );
        }

        $error = $json->error;
        $exception_class = (string) ApiException::getError($status_code, $error->type ?? null);
        $exception_class = 'GoCardlessPro\\Core\\Exception\\' . $exception_class;

        $api_response = new ApiResponse($response);
        throw new $exception_class($api_response);
    }

    /**
     * Recursively maps through an array, casting any booleans to strings, where
     * true should be casted as "true", and false as "false". We use this to
     * prepare query parameters to be sent to the API, since PHP's in-build
     * http_build_query casts booleans as "1" and "" respectively, which is odd.
     *
     * @param array  $query An array to map through, casting booleans to strings
     *
     * @return array The new array with booleans casted to strings
     */
    private function castBooleanValuesToStrings(array $query): array
    {
        return array_map(function ($value) {
            if ($value === true) {
                return "true";
            } elseif ($value === false) {
                return "false";
            } elseif (is_array($value)) {
                return $this->castBooleanValuesToStrings($value);
            } else {
                return $value;
            }
        }, $query);
    }
}
