<?php

/**
  * WARNING: Do not edit by hand, this file was generated by Crank:
  *
  * https://github.com/gocardless/crank
  */

namespace GoCardless\Services;



/**
  *  <a name="api_key_not_active"></a>API keys are designed to be used by any
  *  integrations you build. You should generate a key and then use it to make
  *  requests to the API and set the webhook URL for that integration. They do
  *  not expire, but can be disabled.
  */
class ApiKey extends Base
{
  
  /**
    *  Creates a new API key.
    *
    *  Example URL: /api_keys
    **/
    
    public function docreate($options = array())
    {

      return $this->makeRequest("post", "/api_keys", $options);
    }

  /**
    *  Returns a
    *  [cursor-paginated](https://developer.gocardless.com/pro/#overview-cursor-pagination)
    *  list of your API keys.
    *
    *  Example URL: /api_keys
    **/
    
    public function dolist($options = array())
    {

      return $this->makeRequest("get", "/api_keys", $options);
    }

  /**
    *  Retrieves the details of an existing API key.
    *
    *  Example URL: /api_keys/:identity
    *  
    *  @param identity:  Unique identifier, beginning with "AK"
    **/
    
    public function doget($identity, $options = array())
    {

      $path = $this->subUrl("/api_keys/%v", array(
        "identity" => $identity
      ));

      return $this->makeRequest("get", $path, $options);
    }

  /**
    *  Updates an API key. Only the `name` and `webhook_url` fields are
    *  supported.
    *
    *  Example URL: /api_keys/:identity
    *  
    *  @param identity:  Unique identifier, beginning with "AK"
    **/
    
    public function doupdate($identity, $options = array())
    {

      $path = $this->subUrl("/api_keys/%v", array(
        "identity" => $identity
      ));

      return $this->makeRequest("put", $path, $options);
    }

  /**
    *  Disables an API key. Once disabled, the API key will not be usable to
    *  authenticate any requests, and its `webhook_url` will not receive any
    *  more events.
    *
    *  Example URL: /api_keys/:identity/actions/disable
    *  
    *  @param identity:  Unique identifier, beginning with "AK"
    **/
    
    public function dodisable($identity, $options = array())
    {

      $path = $this->subUrl("/api_keys/%v/actions/disable", array(
        "identity" => $identity
      ));

      return $this->makeRequest("post", $path, $options);
    }



   protected function resourceClass() {
     return '\GoCardless\Resources\ApiKey';
   }

  /**
    *  Get the key the response object is enclosed in in JSON.
    */
    protected function envelopeKey()
    {
      return "api_keys";
    }

}
