<?php
/**
  * WARNING: Do not edit by hand, this file was generated by Crank:
  *
  * https://github.com/gocardless/crank
  */

namespace GoCardless\Services;

/**
  *  Customer objects hold the contact details for a customer. A customer can
  *  have several [customer bank
  *  accounts](https://developer.gocardless.com/pro/#api-endpoints-customer-bank-accounts),
  *  which in turn can have several Direct Debit
  *  [mandates](https://developer.gocardless.com/pro/#api-endpoints-mandates).
  */
class Customer extends Base
{
  
  /**
    *  Creates a new customer object.
    *
    *  Example URL: /customers
    *  @return Customer
    **/
    public function create($params = array(), $headers = array())
    {
        return $this->makeRequest('post', '/customers', $params);
    }

  /**
    *  Returns a
    *  [cursor-paginated](https://developer.gocardless.com/pro/#overview-cursor-pagination)
    *  list of your customers.
    *
    *  Example URL: /customers
    *  @return ListResponse
    **/
    public function do_list($params = array(), $headers = array())
    {
        return $this->makeRequest('get', '/customers', $params);
    }

  /**
    *  Retrieves the details of an existing customer.
    *
    *  Example URL: /customers/:identity
    *
    *  @param identity:  Unique identifier, beginning with "CU".
    *  @return Customer
    **/
    public function get($identity, $params = array(), $headers = array())
    {
        $path = $this->subUrl('/customers/:identity', array(
            'identity' => $identity
        ));

        return $this->makeRequest('get', $path, $params, $headers);
    }

  /**
    *  Updates a customer object. Supports all of the fields supported when
    *  creating a customer.
    *
    *  Example URL: /customers/:identity
    *
    *  @param identity:  Unique identifier, beginning with "CU".
    *  @return Customer
    **/
    public function update($identity, $params = array(), $headers = array())
    {
        $path = $this->subUrl('/customers/:identity', array(
            'identity' => $identity
        ));

        return $this->makeRequest('put', $path, $params, $headers);
    }



  /**
    *  Returns a
    *  [cursor-paginated](https://developer.gocardless.com/pro/#overview-cursor-pagination)
    *  list of your customers.
    *
    *  Example URL: /customers\
    *  @return Paginator
    **/
    public function all($listMax, $options = array())
    {
        return new Paginator($this, $listMax, $this->do_list($options), $options);
    }


   /**
    * Get the resource loading class.
    * Used internally to send http requests.
    *
    * @return string
    */
    protected function resourceClass()
    {
        return '\GoCardless\Resources\Customer';
    }

  /**
    *  Get the key the response object is enclosed in in JSON.
    *  Used internally to wrap and unwrap http requests.
    *
    *  @return string
    */
    protected function envelopeKey()
    {
        return 'customers';
    }
}
