<?php
/**
  * WARNING: Do not edit by hand, this file was generated by Crank:
  *
  * https://github.com/gocardless/crank
  */

namespace GoCardless\Services;

/**
  *  Events are stored for all webhooks. An event refers to a resource which has
  *  been updated, for example a payment which has been collected, or a mandate
  *  which has been transferred.
  */
class Event extends Base
{
  
  /**
    *  Returns a
    *  [cursor-paginated](https://developer.gocardless.com/pro/#overview-cursor-pagination)
    *  list of your events.
    *
    *  Example URL: /events
    **/
    public function do_list($options = array())
    {
        return $this->makeRequest('get', '/events', $options);
    }

  /**
    *  Retrieves the details of a single event.
    *
    *  Example URL: /events/:identity
    *
    *  @param identity:  Unique identifier, beginning with "EV"
    **/
    public function get($identity, $options = array())
    {
        $path = $this->subUrl('/events/:identity', array(
            'identity' => $identity
        ));

        return $this->makeRequest('get', $path, $options);
    }



  /**
    *  Returns a
    *  [cursor-paginated](https://developer.gocardless.com/pro/#overview-cursor-pagination)
    *  list of your events.
    *
    *  Example URL: /events
    **/
    public function all($listMax, $options = array())
    {
        return new Paginator($this, $listMax, $this->do_list($options), $options);
    }


  /**
    * Handles functions in the API that are normally PHP reserved words.
    */
    public function __call($name, $args)
    {
        $attemptName = 'do_' . $name;
        if (method_exists($this, $attemptName)) {
            return call_user_func_array(array($this, $attemptName), $args);
        }
        return false;
    }

  /**
   * Get the resource loading class.
   */
    protected function resourceClass()
    {
        return '\GoCardless\Resources\Event';
    }

  /**
    *  Get the key the response object is enclosed in in JSON.
    */
    protected function envelopeKey()
    {
        return 'events';
    }
}
