<?php
/**
  * WARNING: Do not edit by hand, this file was generated by Crank:
  *
  * https://github.com/gocardless/crank
  */

namespace GoCardless\Services;

/**
  *  Publishable API Keys
  *
  * @method \GoCardless\Core\ListResponse list() list(array $options = array(), array $headers = array()) gets a non-paginated list of models given finder options.
  *
  *  Publishable API keys are designed to be used by the [js
  *  flow](https://developer.gocardless.com/pro/#api-endpoints-customer-bank-account-tokens).
  *  You should generate a key and then use it to make requests to the API. They
  *  do not expire, but can be disabled.
  *  
  *  Publishable API keys only
  *  have permissions to create [customer bank account
  *  tokens](https://developer.gocardless.com/pro/#api-endpoints-customer-bank-account-tokens).
  */
class PublishableApiKey extends Base
{
  
  /**
    *  Create a publishable API key
    *
    *  Creates a publishable API key object.
    *
    *  Example URL: /publishable_api_keys
    *  @return PublishableApiKey
    *  @throws \GoCardless\Core\Error\GoCardlessError GoCardless API or server error, subclasses thereof.
    *  @throws \GoCardless\Core\Error\HttpError PHP Curl transport layer-level errors.
    **/
    public function create($params = array(), $headers = array())
    {
        return $this->make_request('post', '/publishable_api_keys', $params);
    }

  /**
    *  List publishable API keys
    *
    *  Returns a
    *  [cursor-paginated](https://developer.gocardless.com/pro/#overview-cursor-pagination)
    *  list of your publishable API keys
    *
    *  Example URL: /publishable_api_keys
    *  @return \GoCardless\Core\ListResponse
    *  @throws \GoCardless\Core\Error\GoCardlessError GoCardless API or server error, subclasses thereof.
    *  @throws \GoCardless\Core\Error\HttpError PHP Curl transport layer-level errors.
    **/
    public function do_list($params = array(), $headers = array())
    {
        return $this->make_request('get', '/publishable_api_keys', $params);
    }

  /**
    *  Get a single publishable API key
    *
    *  Returns all details about a single publishable API key
    *
    *  Example URL: /publishable_api_keys/:identity
    *
    *  @param identity:  Unique identifier, beginning with "PK"
    *  @return PublishableApiKey
    *  @throws \GoCardless\Core\Error\GoCardlessError GoCardless API or server error, subclasses thereof.
    *  @throws \GoCardless\Core\Error\HttpError PHP Curl transport layer-level errors.
    **/
    public function get($identity, $params = array(), $headers = array())
    {
        $path = $this->sub_url('/publishable_api_keys/:identity', array(
            'identity' => $identity
        ));

        return $this->make_request('get', $path, $params, $headers);
    }

  /**
    *  Update a publishable API key
    *
    *  Updates a publishable API key. Only the `name` fields are supported. Any
    *  other fields passed will be ignored.
    *
    *  Example URL: /publishable_api_keys/:identity
    *
    *  @param identity:  Unique identifier, beginning with "PK"
    *  @return PublishableApiKey
    *  @throws \GoCardless\Core\Error\GoCardlessError GoCardless API or server error, subclasses thereof.
    *  @throws \GoCardless\Core\Error\HttpError PHP Curl transport layer-level errors.
    **/
    public function update($identity, $params = array(), $headers = array())
    {
        $path = $this->sub_url('/publishable_api_keys/:identity', array(
            'identity' => $identity
        ));

        return $this->make_request('put', $path, $params, $headers);
    }

  /**
    *  Disable a publishable API key
    *
    *  Disables a publishable API key. Once disabled, the publishable API key
    *  will not be usable to authenticate any requests.
    *
    *  Example URL: /publishable_api_keys/:identity/actions/disable
    *
    *  @param identity:  Unique identifier, beginning with "PK"
    *  @return PublishableApiKey
    *  @throws \GoCardless\Core\Error\GoCardlessError GoCardless API or server error, subclasses thereof.
    *  @throws \GoCardless\Core\Error\HttpError PHP Curl transport layer-level errors.
    **/
    public function disable($identity, $params = array(), $headers = array())
    {
        $path = $this->sub_url('/publishable_api_keys/:identity/actions/disable', array(
            'identity' => $identity
        ));

        return $this->make_request('post', $path, $params, $headers);
    }



  /**
    *  List publishable API keys
    *
    *  Returns a
    *  [cursor-paginated](https://developer.gocardless.com/pro/#overview-cursor-pagination)
    *  list of your publishable API keys
    *
    *  Example URL: /publishable_api_keys\
    *  @return \GoCardless\Core\Paginator
    **/
    public function all($list_max, $options = array(), $headers = array())
    {
        return new \GoCardless\Core\Paginator($this, $list_max, $this->do_list($options), $options, $headers);
    }


   /**
    * Get the resource loading class.
    * Used internally to send http requests.
    *
    * @return string
    */
    protected function resourceClass()
    {
        return '\GoCardless\Resources\PublishableApiKey';
    }

  /**
    *  Get the key the response object is enclosed in in JSON.
    *  Used internally to wrap and unwrap http requests.
    *
    *  @return string
    */
    protected function envelopeKey()
    {
        return 'publishable_api_keys';
    }
}
