<?php
/**
  * WARNING: Do not edit by hand, this file was generated by Crank:
  *
  * https://github.com/gocardless/crank
  */

namespace GoCardless\Services;

/**
  *  Refund objects represent (partial) refunds of a
  *  [payment](https://developer.gocardless.com/pro/#api-endpoints-payment) back
  *  to the
  *  [customer](https://developer.gocardless.com/pro/#api-endpoints-customers).

  *   *  
  *  The API allows you to create, show, list and update your
  *  refunds.
  *  
  *  GoCardless will notify you via a
  *  [webhook](https://developer.gocardless.com/pro/#webhooks) whenever a refund
  *  is created.
  *  
  *  _Note:_ A payment that has been (partially) refunded
  *  can still receive a late failure or chargeback from the banks.
  */
class Refund extends Base
{
  
  /**
    *  Creates a new refund object.
    *  
    *  This fails with:<a
    *  name="refund_payment_invalid_state"></a><a
    *  name="total_amount_confirmation_invalid"></a>
    *  
    *  -
    *  `refund_payment_invalid_state` error if the linked
    *  [payment](https://developer.gocardless.com/pro/#api-endpoints-payments)
    *  isn't either `confirmed` or `paid_out`.
    *  
    *  -
    *  `total_amount_confirmation_invalid` if the confirmation amount doesn't
    *  match the total amount refunded for the payment. This safeguard is there
    *  to prevent two processes from creating refunds without awareness of each
    *  other.
    *  
    *
    *  Example URL: /refunds
    *  @return Refund
    **/
    public function create($params = array(), $headers = array())
    {
        return $this->makeRequest('post', '/refunds', $params);
    }

  /**
    *  Returns a
    *  [cursor-paginated](https://developer.gocardless.com/pro/#overview-cursor-pagination)
    *  list of your refunds.
    *
    *  Example URL: /refunds
    *  @return ListResponse
    **/
    public function do_list($params = array(), $headers = array())
    {
        return $this->makeRequest('get', '/refunds', $params);
    }

  /**
    *  Retrieves all details for a single refund
    *
    *  Example URL: /refunds/:identity
    *
    *  @param identity:  Unique identifier, beginning with "RF"
    *  @return Refund
    **/
    public function get($identity, $params = array(), $headers = array())
    {
        $path = $this->subUrl('/refunds/:identity', array(
            'identity' => $identity
        ));

        return $this->makeRequest('get', $path, $params, $headers);
    }

  /**
    *  Updates a refund object.
    *
    *  Example URL: /refunds/:identity
    *
    *  @param identity:  Unique identifier, beginning with "RF"
    *  @return Refund
    **/
    public function update($identity, $params = array(), $headers = array())
    {
        $path = $this->subUrl('/refunds/:identity', array(
            'identity' => $identity
        ));

        return $this->makeRequest('put', $path, $params, $headers);
    }



  /**
    *  Returns a
    *  [cursor-paginated](https://developer.gocardless.com/pro/#overview-cursor-pagination)
    *  list of your refunds.
    *
    *  Example URL: /refunds\
    *  @return Paginator
    **/
    public function all($listMax, $options = array())
    {
        return new Paginator($this, $listMax, $this->do_list($options), $options);
    }


   /**
    * Get the resource loading class.
    * Used internally to send http requests.
    *
    * @return string
    */
    protected function resourceClass()
    {
        return '\GoCardless\Resources\Refund';
    }

  /**
    *  Get the key the response object is enclosed in in JSON.
    *  Used internally to wrap and unwrap http requests.
    *
    *  @return string
    */
    protected function envelopeKey()
    {
        return 'refunds';
    }
}
