<?php
/**
  * WARNING: Do not edit by hand, this file was generated by Crank:
  *
  * https://github.com/gocardless/crank
  */

namespace GoCardless\Resources;

/**
  *  Payouts represent transfers from GoCardless to a
  *  [creditor](https://developer.gocardless.com/pro/#api-endpoints-creditors).
  *  Each payout contains the funds collected from one or many
  *  [payments](https://developer.gocardless.com/pro/#api-endpoints-payments).
  *  Payouts are created automatically after a payment has been successfully
  *  collected.
  */
class Payout
{
  
    
    private $data;
    private $response;

    public function __construct($data, $response = null)
    {
      if ($data === null)
      {
        throw new \Exception('Data cannot be null');
      }
      $this->response = $response;
      $this->data = $data;
    }
  
    
    
    public function amount()
    {
      return $this->data->amount;
    }
  
    
    public function created_at()
    {
      return $this->data->created_at;
    }
  
    
    public function currency()
    {
      return $this->data->currency;
    }
  
    
    public function id()
    {
      return $this->data->id;
    }
  
    
    public function links()
    {
      return $this->data->links;
    }
  
    
    public function reference()
    {
      return $this->data->reference;
    }
  
    
    public function status()
    {
      return $this->data->status;
    }
  
    
    public function response() {
      return $this->response;
    }


}
