<?php
//
// WARNING: Do not edit by hand, this file was generated by Crank:
// https://github.com/gocardless/crank
//

namespace GoCardlessPro\Integration;

class BankDetailsLookupsTest extends IntegrationTestBase
{
    public function setUp()
    {
        $this->clientAndFixtureSetup('bank_details_lookups');
    }

    public function testResourceExists()
    {
        $obj = new \GoCardlessPro\Resources\BankDetailsLookup(null);
        $this->assertNotNull($obj);
    }

    public function testBankDetailsLookupsCreate()
    {
        $fixture = $this->stubResponse('create');

        $func_array = array_values((array) $fixture->url_params);
        $resourceService = $this->client->bank_details_lookups();
        $response = call_user_func_array(array($resourceService, 'create'), $func_array);

        $body = $fixture->body->bank_details_lookups;

    
        $this->assertInstanceOf('\GoCardlessPro\Resources\BankDetailsLookup', $response);

        $this->matchDeepResponse($body->available_debit_schemes, $response->available_debit_schemes());
        $this->matchDeepResponse($body->bank_name, $response->bank_name());
        $this->matchDeepResponse($body->bic, $response->bic());
    

        $this->assertTrue($this->hasCheckedCurl);
    }
}
