<?php
//
// WARNING: Do not edit by hand, this file was generated by Crank:
// https://github.com/gocardless/crank
//

namespace GoCardlessPro\Integration;

class MandatesTest extends IntegrationTestBase
{
    public function setUp()
    {
        $this->clientAndFixtureSetup('mandates');
    }

    public function testResourceExists()
    {
        $obj = new \GoCardlessPro\Resources\Mandate(null);
        $this->assertNotNull($obj);
    }

    public function testMandatesCreate()
    {
        $fixture = $this->stubResponse('create');

        $func_array = array_values((array) $fixture->url_params);
        $resourceService = $this->client->mandates();
        $response = call_user_func_array(array($resourceService, 'create'), $func_array);

        $body = $fixture->body->mandates;

    
        $this->assertInstanceOf('\GoCardlessPro\Resources\Mandate', $response);

        $this->matchDeepResponse($body->created_at, $response->created_at());
        $this->matchDeepResponse($body->id, $response->id());
        $this->matchDeepResponse($body->links, $response->links());
        $this->matchDeepResponse($body->metadata, $response->metadata());
        $this->matchDeepResponse($body->next_possible_charge_date, $response->next_possible_charge_date());
        $this->matchDeepResponse($body->reference, $response->reference());
        $this->matchDeepResponse($body->scheme, $response->scheme());
        $this->matchDeepResponse($body->status, $response->status());
    

        $this->assertTrue($this->hasCheckedCurl);
    }

    public function testMandatesList()
    {
        $fixture = $this->stubResponse('list');

        $func_array = array_values((array) $fixture->url_params);
        $resourceService = $this->client->mandates();
        $response = call_user_func_array(array($resourceService, 'list'), $func_array);

        $body = $fixture->body->mandates;

    
        $records = $response->records();
        $this->assertInstanceOf('\GoCardlessPro\Core\ListResponse', $response);
        $this->assertInstanceOf('\GoCardlessPro\Resources\Mandate', $records[0]);

        $this->assertEquals($fixture->body->meta->cursors->before, $response->meta()->cursors()->before());
        $this->assertEquals($fixture->body->meta->cursors->after, $response->meta()->cursors()->after());
    

    
        foreach (range(0, count($body) - 1) as $num) {
            $record = $records[$num];
            $this->matchDeepResponse($body[$num]->created_at, $record->created_at());
            $this->matchDeepResponse($body[$num]->id, $record->id());
            $this->matchDeepResponse($body[$num]->links, $record->links());
            $this->matchDeepResponse($body[$num]->metadata, $record->metadata());
            $this->matchDeepResponse($body[$num]->next_possible_charge_date, $record->next_possible_charge_date());
            $this->matchDeepResponse($body[$num]->reference, $record->reference());
            $this->matchDeepResponse($body[$num]->scheme, $record->scheme());
            $this->matchDeepResponse($body[$num]->status, $record->status());
            
        }

        $this->assertTrue($this->hasCheckedCurl);
    }

    public function testMandatesGet()
    {
        $fixture = $this->stubResponse('get');

        $func_array = array_values((array) $fixture->url_params);
        $resourceService = $this->client->mandates();
        $response = call_user_func_array(array($resourceService, 'get'), $func_array);

        $body = $fixture->body->mandates;

    
        $this->assertInstanceOf('\GoCardlessPro\Resources\Mandate', $response);

        $this->matchDeepResponse($body->created_at, $response->created_at());
        $this->matchDeepResponse($body->id, $response->id());
        $this->matchDeepResponse($body->links, $response->links());
        $this->matchDeepResponse($body->metadata, $response->metadata());
        $this->matchDeepResponse($body->next_possible_charge_date, $response->next_possible_charge_date());
        $this->matchDeepResponse($body->reference, $response->reference());
        $this->matchDeepResponse($body->scheme, $response->scheme());
        $this->matchDeepResponse($body->status, $response->status());
    

        $this->assertTrue($this->hasCheckedCurl);
    }

    public function testMandatesUpdate()
    {
        $fixture = $this->stubResponse('update');

        $func_array = array_values((array) $fixture->url_params);
        $resourceService = $this->client->mandates();
        $response = call_user_func_array(array($resourceService, 'update'), $func_array);

        $body = $fixture->body->mandates;

    
        $this->assertInstanceOf('\GoCardlessPro\Resources\Mandate', $response);

        $this->matchDeepResponse($body->created_at, $response->created_at());
        $this->matchDeepResponse($body->id, $response->id());
        $this->matchDeepResponse($body->links, $response->links());
        $this->matchDeepResponse($body->metadata, $response->metadata());
        $this->matchDeepResponse($body->next_possible_charge_date, $response->next_possible_charge_date());
        $this->matchDeepResponse($body->reference, $response->reference());
        $this->matchDeepResponse($body->scheme, $response->scheme());
        $this->matchDeepResponse($body->status, $response->status());
    

        $this->assertTrue($this->hasCheckedCurl);
    }

    public function testMandatesCancel()
    {
        $fixture = $this->stubResponse('cancel');

        $func_array = array_values((array) $fixture->url_params);
        $resourceService = $this->client->mandates();
        $response = call_user_func_array(array($resourceService, 'cancel'), $func_array);

        $body = $fixture->body->mandates;

    
        $this->assertInstanceOf('\GoCardlessPro\Resources\Mandate', $response);

        $this->matchDeepResponse($body->created_at, $response->created_at());
        $this->matchDeepResponse($body->id, $response->id());
        $this->matchDeepResponse($body->links, $response->links());
        $this->matchDeepResponse($body->metadata, $response->metadata());
        $this->matchDeepResponse($body->next_possible_charge_date, $response->next_possible_charge_date());
        $this->matchDeepResponse($body->reference, $response->reference());
        $this->matchDeepResponse($body->scheme, $response->scheme());
        $this->matchDeepResponse($body->status, $response->status());
    

        $this->assertTrue($this->hasCheckedCurl);
    }

    public function testMandatesReinstate()
    {
        $fixture = $this->stubResponse('reinstate');

        $func_array = array_values((array) $fixture->url_params);
        $resourceService = $this->client->mandates();
        $response = call_user_func_array(array($resourceService, 'reinstate'), $func_array);

        $body = $fixture->body->mandates;

    
        $this->assertInstanceOf('\GoCardlessPro\Resources\Mandate', $response);

        $this->matchDeepResponse($body->created_at, $response->created_at());
        $this->matchDeepResponse($body->id, $response->id());
        $this->matchDeepResponse($body->links, $response->links());
        $this->matchDeepResponse($body->metadata, $response->metadata());
        $this->matchDeepResponse($body->next_possible_charge_date, $response->next_possible_charge_date());
        $this->matchDeepResponse($body->reference, $response->reference());
        $this->matchDeepResponse($body->scheme, $response->scheme());
        $this->matchDeepResponse($body->status, $response->status());
    

        $this->assertTrue($this->hasCheckedCurl);
    }
}
