name: build
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test_library:
    strategy:
      fail-fast: false
      matrix:
        version: [8.2, 8.3, 8.4, 8.5]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.version }}
      - run: composer install --no-interaction
      - name: Test Library
        run: ./vendor/phpunit/phpunit/phpunit

  all-tests-passed:
    name: all-tests-passed
    runs-on: ubuntu-latest
    needs: [test_library]
    if: always()
    steps:
      - name: Check test_library job status
        run: |
          if [ "${{ needs.test_library.result }}" != "success" ]; then
            echo "test_library job did not succeed"
            exit 1
          fi
